#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: actions_animset_str

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct actions_animset_str.actions_animset_str
// 0x0028 (0x0028 - 0x0000)
struct Factions_animset_str final
{
public:
	class UAnimMontage*                           sheathe_2_95E6F74C4ED56EEA68455493BA193A8E;        // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           unsheathe_4_ECE57E964039C9A89D7D54859CF22FF8;      // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           fake_unsheathe_7_88D85BBC44B20E10646FF1B14D58700B; // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           potion_drink_10_5779390A476DF7A07A955396D8D38B5C;  // 0x0018(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           new_potion_drink_13_302F77F34FD65D1052D8AEA6F1213A8D; // 0x0020(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Factions_animset_str;

SDK_NAMESPACE_END
