#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AtmosphereCard

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct AtmosphereCard.AtmosphereCard
// 0x0050 (0x0050 - 0x0000)
struct FAtmosphereCard final
{
public:
	float                                         rotation_2_8052D2974EC077BDC1CDAA86B6100559;       // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         distance_37_51427D7745536BA324781AA05348F8BA;      // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         height_39_30071EE14958798B969341AC95B7BBE2;        // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                scale_33_347235E7472E95BC9DA2598CD7277B5D;         // 0x000C(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         scale_multiplier_36_3F0E244A4C60D336D46E3493C7BC1F9C; // 0x0018(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UStaticMesh>             mesh_27_9416FB6B441CEF3DC1CDACA733B793B2;          // 0x0020(0x0028)(Edit, BlueprintVisible, HasGetValueTypeHash)
	class UMaterialInstance*                      material_31_F734CC734A5BD87AE6E8C8925C221E58;      // 0x0048(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_FAtmosphereCard;

SDK_NAMESPACE_END
