#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: attack_button_held_time_ec

#include "Basic.hpp"

#include "Archon_structs.hpp"
#include "Archon_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass attack_button_held_time_ec.attack_button_held_time_ec_C
// 0x0008 (0x0038 - 0x0030)
class Uattack_button_held_time_ec_C final : public UArchonTransitionCondition
{
public:
	EArchonAttackActionKey                        ActionKey;                                         // 0x0030(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EArchonCompareOperator                        Operator;                                          // 0x0031(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_32[0x2];                                       // 0x0032(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         RValue;                                            // 0x0034(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool Evaluate(const struct FConditionParams& Params_0) const;
	class FString GetConditionName() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("attack_button_held_time_ec_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"attack_button_held_time_ec_C")
	}
	static class Uattack_button_held_time_ec_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Uattack_button_held_time_ec_C>();
	}
};
DUMPER7_ASSERTS_Uattack_button_held_time_ec_C;

SDK_NAMESPACE_END
