#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: attribute_function_library

#include "Basic.hpp"

#include "Archon_structs.hpp"
#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass attribute_function_library.attribute_function_library_C
// 0x0000 (0x0028 - 0x0028)
class Uattribute_function_library_C final : public UBlueprintFunctionLibrary
{
public:
	static void GetAttributeName(const struct FGameplayAttribute& Attribute, class UObject* __WorldContext, class FString* AttributeName);
	static void GetWeaponPowerAttributes(bool IncludeGlobalPower, bool IncludeGlobalElementalPower, class UObject* __WorldContext, TArray<struct FGameplayAttribute>* WeaponPowerAttributes);
	static void GetPowerAttributeForElement(EArchonElementType ElementType, class UObject* __WorldContext, struct FGameplayAttribute* PowerAttribute);

	static void GetPostMultiplicationModifiers(bool SelfIfTrue_TargetIfFalse, class AActor* SourceActor, class AActor* TargetActor, class UObject* __WorldContext, TArray<float>* PostMultiplicationModifiers);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("attribute_function_library_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"attribute_function_library_C")
	}
	static class Uattribute_function_library_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Uattribute_function_library_C>();
	}
};
DUMPER7_ASSERTS_Uattribute_function_library_C;

SDK_NAMESPACE_END
