#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: base_staticfarshadows_component

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function base_staticfarshadows_component.base_staticfarshadows_component_C.ExecuteUbergraph_base_staticfarshadows_component
// 0x0008 (0x0008 - 0x0000)
struct base_staticfarshadows_component_C_ExecuteUbergraph_base_staticfarshadows_component final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DeltaSeconds;                         // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_base_staticfarshadows_component_C_ExecuteUbergraph_base_staticfarshadows_component;

// Function base_staticfarshadows_component.base_staticfarshadows_component_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct base_staticfarshadows_component_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_base_staticfarshadows_component_C_ReceiveTick;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
