#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BForBug

#include "Basic.hpp"

#include "BForBug_classes.hpp"
#include "BForBug_parameters.hpp"


SDK_NAMESPACE_START

// Function BForBug.BForBugStatics.GatherAllBugData
// (Final, Native, Static, Private, BlueprintCallable)
// Parameters:
// TArray<struct FBugData>                 ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

TArray<struct FBugData> UBForBugStatics::GatherAllBugData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BForBugStatics", "GatherAllBugData");

	Params::BForBugStatics_GatherAllBugData Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}


// Function BForBug.BForBugStatics.GetBugAttachment
// (Final, Native, Static, Private, HasOutParams, BlueprintCallable)
// Parameters:
// TScriptInterface<class IBugDataInterface>BugDataInterface                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, NativeAccessSpecifierPublic)
// class FString*                          OutAttachmentName                                      (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString*                          OutAttachmentBody                                      (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UBForBugStatics::GetBugAttachment(TScriptInterface<class IBugDataInterface> BugDataInterface, class FString* OutAttachmentName, class FString* OutAttachmentBody)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BForBugStatics", "GetBugAttachment");

	Params::BForBugStatics_GetBugAttachment Parms{};

	Parms.BugDataInterface = BugDataInterface;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (OutAttachmentName != nullptr)
		*OutAttachmentName = std::move(Parms.OutAttachmentName);

	if (OutAttachmentBody != nullptr)
		*OutAttachmentBody = std::move(Parms.OutAttachmentBody);

	return Parms.ReturnValue;
}


// Function BForBug.BForBugStatics.GetBugSummaryInfo
// (Final, Native, Static, Private, HasOutParams, BlueprintCallable)
// Parameters:
// TScriptInterface<class IBugDataInterface>BugDataInterface                                       (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, NativeAccessSpecifierPublic)
// class FString*                          OutPrefix                                              (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString*                          OutData                                                (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UBForBugStatics::GetBugSummaryInfo(TScriptInterface<class IBugDataInterface> BugDataInterface, class FString* OutPrefix, class FString* OutData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BForBugStatics", "GetBugSummaryInfo");

	Params::BForBugStatics_GetBugSummaryInfo Parms{};

	Parms.BugDataInterface = BugDataInterface;

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	if (OutPrefix != nullptr)
		*OutPrefix = std::move(Parms.OutPrefix);

	if (OutData != nullptr)
		*OutData = std::move(Parms.OutData);

	return Parms.ReturnValue;
}


// Function BForBug.BugDataInterface.GetBugAttachmentTextBlueprint
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString*                          OutAttachmentName                                      (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString*                          OutAttachmentBody                                      (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool IBugDataInterface::GetBugAttachmentTextBlueprint(class FString* OutAttachmentName, class FString* OutAttachmentBody)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BugDataInterface", "GetBugAttachmentTextBlueprint");

	Params::BugDataInterface_GetBugAttachmentTextBlueprint Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (OutAttachmentName != nullptr)
		*OutAttachmentName = std::move(Parms.OutAttachmentName);

	if (OutAttachmentBody != nullptr)
		*OutAttachmentBody = std::move(Parms.OutAttachmentBody);

	return Parms.ReturnValue;
}


// Function BForBug.BugDataInterface.GetBugSummaryInfoBlueprint
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString*                          OutPrefix                                              (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString*                          OutData                                                (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool IBugDataInterface::GetBugSummaryInfoBlueprint(class FString* OutPrefix, class FString* OutData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("BugDataInterface", "GetBugSummaryInfoBlueprint");

	Params::BugDataInterface_GetBugSummaryInfoBlueprint Parms{};

	AsUObject()->ProcessEvent(Func, &Parms);

	if (OutPrefix != nullptr)
		*OutPrefix = std::move(Parms.OutPrefix);

	if (OutData != nullptr)
		*OutData = std::move(Parms.OutData);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
