#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: blackboard_math_operators

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum blackboard_math_operators.blackboard_math_operators
// NumValues: 0x0005
enum class Eblackboard_math_operators : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	blackboard_math_MAX                      = 4,
};

SDK_NAMESPACE_END
