#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPGS_ArchonStoryMissions_GameState

#include "Basic.hpp"

#include "BPGS_ArchonExploration_GameState_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BPGS_ArchonStoryMissions_GameState.BPGS_ArchonStoryMissions_GameState_C
// 0x0000 (0x04E8 - 0x04E8)
class ABPGS_ArchonStoryMissions_GameState_C final : public ABPGS_ArchonExploration_GameState_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPGS_ArchonStoryMissions_GameState_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPGS_ArchonStoryMissions_GameState_C")
	}
	static class ABPGS_ArchonStoryMissions_GameState_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABPGS_ArchonStoryMissions_GameState_C>();
	}
};
DUMPER7_ASSERTS_ABPGS_ArchonStoryMissions_GameState_C;

SDK_NAMESPACE_END
