#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_camera

#include "Basic.hpp"

#include "player_camera_state_enum_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BPI_camera.BPI_camera_C.ToggleSprintCamera
// 0x0001 (0x0001 - 0x0000)
struct BPI_camera_C_ToggleSprintCamera final
{
public:
	bool                                          On;                                                // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BPI_camera_C_ToggleSprintCamera;

// Function BPI_camera.BPI_camera_C.SetCameraState
// 0x0001 (0x0001 - 0x0000)
struct BPI_camera_C_SetCameraState final
{
public:
	Eplayer_camera_state_enum                     CameraState;                                       // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_camera_C_SetCameraState;

// Function BPI_camera.BPI_camera_C.SetDesiredCameraValues
// 0x0004 (0x0004 - 0x0000)
struct BPI_camera_C_SetDesiredCameraValues final
{
public:
	float                                         DesiredCameraLagSpeed;                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_camera_C_SetDesiredCameraValues;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
