#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPI_HUD

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "pickup_notification_item_number_struct_structs.hpp"
#include "Archon_structs.hpp"
#include "gamemode_notify_data_structs.hpp"
#include "progression_award_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BPI_HUD.BPI_HUD_C.Show HUD
// 0x0001 (0x0001 - 0x0000)
struct BPI_HUD_C_Show_HUD final
{
public:
	bool                                          Game_Input;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BPI_HUD_C_Show_HUD;

// Function BPI_HUD.BPI_HUD_C.Show Store
// 0x0048 (0x0048 - 0x0000)
struct BPI_HUD_C_Show_Store final
{
public:
	class FString                                 Path;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Source;                                            // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          ReturntoGameplay_OnClose;                          // 0x0020(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 SourceItem;                                        // 0x0028(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 PlatAmount;                                        // 0x0038(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_HUD_C_Show_Store;

// Function BPI_HUD.BPI_HUD_C.Progression Awarded
// 0x0018 (0x0018 - 0x0000)
struct BPI_HUD_C_Progression_Awarded final
{
public:
	TArray<struct Fprogression_award>             Grants;                                            // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
	class UCanvasPanel*                           ContainerWidget;                                   // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_HUD_C_Progression_Awarded;

// Function BPI_HUD.BPI_HUD_C.Try Chat Input
// 0x0002 (0x0002 - 0x0000)
struct BPI_HUD_C_Try_Chat_Input final
{
public:
	bool                                          FromGameplay;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Success;                                           // 0x0001(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BPI_HUD_C_Try_Chat_Input;

// Function BPI_HUD.BPI_HUD_C.GetPaperdollScene
// 0x0008 (0x0008 - 0x0000)
struct BPI_HUD_C_GetPaperdollScene final
{
public:
	class UActorComponent*                        PaperDollScene;                                    // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_HUD_C_GetPaperdollScene;

// Function BPI_HUD.BPI_HUD_C.QuickSlotUseFailed
// 0x0001 (0x0001 - 0x0000)
struct BPI_HUD_C_QuickSlotUseFailed final
{
public:
	ELoadoutQuickItemSlot                         QuickslotIndex;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_HUD_C_QuickSlotUseFailed;

// Function BPI_HUD.BPI_HUD_C.AddGamemodeNotification
// 0x0090 (0x0090 - 0x0000)
struct BPI_HUD_C_AddGamemodeNotification final
{
public:
	struct Fgamemode_notify_data                  GamemodeNotifyData;                                // 0x0000(0x0090)(BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_HUD_C_AddGamemodeNotification;

// Function BPI_HUD.BPI_HUD_C.AddCustomItemNotification
// 0x0030 (0x0030 - 0x0000)
struct BPI_HUD_C_AddCustomItemNotification final
{
public:
	struct Fpickup_notification_item_number_struct ItemData;                                         // 0x0000(0x0030)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_HUD_C_AddCustomItemNotification;

// Function BPI_HUD.BPI_HUD_C.AddTutorialPopup
// 0x0008 (0x0008 - 0x0000)
struct BPI_HUD_C_AddTutorialPopup final
{
public:
	class UWidget*                                Tutorial;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_HUD_C_AddTutorialPopup;

// Function BPI_HUD.BPI_HUD_C.GetHUDVisibility
// 0x0001 (0x0001 - 0x0000)
struct BPI_HUD_C_GetHUDVisibility final
{
public:
	ESlateVisibility                              Visibility;                                        // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BPI_HUD_C_GetHUDVisibility;

// Function BPI_HUD.BPI_HUD_C.Close Chat Window
// 0x0001 (0x0001 - 0x0000)
struct BPI_HUD_C_Close_Chat_Window final
{
public:
	bool                                          bOnlyIfNotFocusable;                               // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_BPI_HUD_C_Close_Chat_Window;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
