#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: bpw_LowHealthVignette

#include "Basic.hpp"

#include "bpw_LowHealthVignette_classes.hpp"
#include "bpw_LowHealthVignette_parameters.hpp"


SDK_NAMESPACE_START

// Function bpw_LowHealthVignette.bpw_LowHealthVignette_C.ExecuteUbergraph_bpw_LowHealthVignette
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ubpw_LowHealthVignette_C::ExecuteUbergraph_bpw_LowHealthVignette(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("bpw_LowHealthVignette_C", "ExecuteUbergraph_bpw_LowHealthVignette");

	Params::bpw_LowHealthVignette_C_ExecuteUbergraph_bpw_LowHealthVignette Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function bpw_LowHealthVignette.bpw_LowHealthVignette_C.CallGlobalEvent3rdpartyHookHealthLow
// (Event, Protected, BlueprintEvent)

void Ubpw_LowHealthVignette_C::CallGlobalEvent3rdpartyHookHealthLow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("bpw_LowHealthVignette_C", "CallGlobalEvent3rdpartyHookHealthLow");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
