#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: cell_text_tokenizer

#include "Basic.hpp"

#include "cell_text_tokenizer_classes.hpp"
#include "cell_text_tokenizer_parameters.hpp"


SDK_NAMESPACE_START

// Function cell_text_tokenizer.cell_text_tokenizer_C.FormatFloatValue
// (Private, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// float                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   MaxFractionalDigits                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText*                            Formatted                                              (Parm, OutParm)

void Ucell_text_tokenizer_C::FormatFloatValue(float Value, int32 MaxFractionalDigits, class FText* Formatted) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("cell_text_tokenizer_C", "FormatFloatValue");

	Params::cell_text_tokenizer_C_FormatFloatValue Parms{};

	Parms.Value = Value;
	Parms.MaxFractionalDigits = MaxFractionalDigits;

	UObject::ProcessEvent(Func, &Parms);

	if (Formatted != nullptr)
		*Formatted = std::move(Parms.Formatted);
}


// Function cell_text_tokenizer.cell_text_tokenizer_C.GetTokenSubstitution
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UObject*                          WorldContextObject                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             Token                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    IsWithinSubstitution                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// class FString*                          SubstitutionText                                       (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)
// bool*                                   RetainBrackets                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool Ucell_text_tokenizer_C::GetTokenSubstitution(class UObject* WorldContextObject, class FName Token, bool IsWithinSubstitution, class FString* SubstitutionText, bool* RetainBrackets) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("cell_text_tokenizer_C", "GetTokenSubstitution");

	Params::cell_text_tokenizer_C_GetTokenSubstitution Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.Token = Token;
	Parms.IsWithinSubstitution = IsWithinSubstitution;

	UObject::ProcessEvent(Func, &Parms);

	if (SubstitutionText != nullptr)
		*SubstitutionText = std::move(Parms.SubstitutionText);

	if (RetainBrackets != nullptr)
		*RetainBrackets = Parms.RetainBrackets;

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
