#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: cinematic_exit_transition_type_enum

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum cinematic_exit_transition_type_enum.cinematic_exit_transition_type_enum
// NumValues: 0x0004
enum class Ecinematic_exit_transition_type_enum : uint8
{
	NewEnumerator1                           = 0,
	NewEnumerator2                           = 1,
	NewEnumerator3                           = 2,
	cinematic_exit_transition_type_MAX       = 3,
};

SDK_NAMESPACE_END
