#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: content_area_tracker_bpc

#include "Basic.hpp"

#include "content_area_tracker_bpc_classes.hpp"
#include "content_area_tracker_bpc_parameters.hpp"


SDK_NAMESPACE_START

// Function content_area_tracker_bpc.content_area_tracker_bpc_C.ExecuteUbergraph_content_area_tracker_bpc
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ucontent_area_tracker_bpc_C::ExecuteUbergraph_content_area_tracker_bpc(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("content_area_tracker_bpc_C", "ExecuteUbergraph_content_area_tracker_bpc");

	Params::content_area_tracker_bpc_C_ExecuteUbergraph_content_area_tracker_bpc Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function content_area_tracker_bpc.content_area_tracker_bpc_C.UpdateClosestArea
// (BlueprintCallable, BlueprintEvent)

void Ucontent_area_tracker_bpc_C::UpdateClosestArea()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("content_area_tracker_bpc_C", "UpdateClosestArea");

	UObject::ProcessEvent(Func, nullptr);
}


// Function content_area_tracker_bpc.content_area_tracker_bpc_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void Ucontent_area_tracker_bpc_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("content_area_tracker_bpc_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function content_area_tracker_bpc.content_area_tracker_bpc_C.AuthTryChangeArea
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           NewArea                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ucontent_area_tracker_bpc_C::AuthTryChangeArea(class AActor* NewArea)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("content_area_tracker_bpc_C", "AuthTryChangeArea");

	Params::content_area_tracker_bpc_C_AuthTryChangeArea Parms{};

	Parms.NewArea = NewArea;

	UObject::ProcessEvent(Func, &Parms);
}


// Function content_area_tracker_bpc.content_area_tracker_bpc_C.Get State for Area
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           AreaActor                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EPlayerAreaState*                       AreaState_0                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ucontent_area_tracker_bpc_C::Get_State_for_Area(class AActor* AreaActor, EPlayerAreaState* AreaState_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("content_area_tracker_bpc_C", "Get State for Area");

	Params::content_area_tracker_bpc_C_Get_State_for_Area Parms{};

	Parms.AreaActor = AreaActor;

	UObject::ProcessEvent(Func, &Parms);

	if (AreaState_0 != nullptr)
		*AreaState_0 = Parms.AreaState_0;
}


// Function content_area_tracker_bpc.content_area_tracker_bpc_C.GetInRadiusStates
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Area                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   InInnerRadius_0                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool*                                   InOuterRadius_0                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void Ucontent_area_tracker_bpc_C::GetInRadiusStates(class AActor* Area, bool* InInnerRadius_0, bool* InOuterRadius_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("content_area_tracker_bpc_C", "GetInRadiusStates");

	Params::content_area_tracker_bpc_C_GetInRadiusStates Parms{};

	Parms.Area = Area;

	UObject::ProcessEvent(Func, &Parms);

	if (InInnerRadius_0 != nullptr)
		*InInnerRadius_0 = Parms.InInnerRadius_0;

	if (InOuterRadius_0 != nullptr)
		*InOuterRadius_0 = Parms.InOuterRadius_0;
}


// Function content_area_tracker_bpc.content_area_tracker_bpc_C.AuthTrySetAreaState
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EPlayerAreaState                        NewAreaState                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Ucontent_area_tracker_bpc_C::AuthTrySetAreaState(EPlayerAreaState NewAreaState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("content_area_tracker_bpc_C", "AuthTrySetAreaState");

	Params::content_area_tracker_bpc_C_AuthTrySetAreaState Parms{};

	Parms.NewAreaState = NewAreaState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function content_area_tracker_bpc.content_area_tracker_bpc_C.OnRep_AreaState
// (BlueprintCallable, BlueprintEvent)

void Ucontent_area_tracker_bpc_C::OnRep_AreaState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("content_area_tracker_bpc_C", "OnRep_AreaState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function content_area_tracker_bpc.content_area_tracker_bpc_C.OnRep_CurrentArea
// (BlueprintCallable, BlueprintEvent)

void Ucontent_area_tracker_bpc_C::OnRep_CurrentArea()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("content_area_tracker_bpc_C", "OnRep_CurrentArea");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
