#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: dp_near_target_ec

#include "Basic.hpp"

#include "Archon_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass dp_near_target_ec.dp_near_target_ec_C
// 0x0000 (0x0030 - 0x0030)
class Udp_near_target_ec_C final : public UArchonTransitionCondition
{
public:
	bool Evaluate(const struct FConditionParams& Params_0) const;
	class FString GetConditionName() const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("dp_near_target_ec_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"dp_near_target_ec_C")
	}
	static class Udp_near_target_ec_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Udp_near_target_ec_C>();
	}
};
DUMPER7_ASSERTS_Udp_near_target_ec_C;

SDK_NAMESPACE_END
