#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: dynamic_cinematic_component_bp

#include "Basic.hpp"

#include "dynamic_cinematic_component_bp_classes.hpp"
#include "dynamic_cinematic_component_bp_parameters.hpp"


SDK_NAMESPACE_START

// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.ExecuteUbergraph_dynamic_cinematic_component_bp
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Udynamic_cinematic_component_bp_C::ExecuteUbergraph_dynamic_cinematic_component_bp(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "ExecuteUbergraph_dynamic_cinematic_component_bp");

	Params::dynamic_cinematic_component_bp_C_ExecuteUbergraph_dynamic_cinematic_component_bp Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.EventBankLoadCompleteCallback
// (BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::EventBankLoadCompleteCallback()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "EventBankLoadCompleteCallback");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.LoadBankCallback
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EAkResult                               Result                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Udynamic_cinematic_component_bp_C::LoadBankCallback(EAkResult Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "LoadBankCallback");

	Params::dynamic_cinematic_component_bp_C_LoadBankCallback Parms{};

	Parms.Result = Result;

	UObject::ProcessEvent(Func, &Parms);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.LoadBanks
// (BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::LoadBanks()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "LoadBanks");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.FadeToBlackComplete
// (BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::FadeToBlackComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "FadeToBlackComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.CacheCameraTransform
// (BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::CacheCameraTransform()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "CacheCameraTransform");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.AuthPositionActorsAtEnd
// (BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::AuthPositionActorsAtEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "AuthPositionActorsAtEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.ToggleShowSequenceTime
// (BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::ToggleShowSequenceTime()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "ToggleShowSequenceTime");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.OnCameraCut
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCameraComponent*                 CameraComponent                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Udynamic_cinematic_component_bp_C::OnCameraCut(class UCameraComponent* CameraComponent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "OnCameraCut");

	Params::dynamic_cinematic_component_bp_C_OnCameraCut Parms{};

	Parms.CameraComponent = CameraComponent;

	UObject::ProcessEvent(Func, &Parms);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.BindNewReplacementActors
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<class UClass*>&            NewProxyActors                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// const TArray<class AActor*>&            NewReplacementActors                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)

void Udynamic_cinematic_component_bp_C::BindNewReplacementActors(const TArray<class UClass*>& NewProxyActors, const TArray<class AActor*>& NewReplacementActors)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "BindNewReplacementActors");

	Params::dynamic_cinematic_component_bp_C_BindNewReplacementActors Parms{};

	Parms.NewProxyActors = std::move(NewProxyActors);
	Parms.NewReplacementActors = std::move(NewReplacementActors);

	UObject::ProcessEvent(Func, &Parms);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.BlendCameraOut
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   BlendTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           NewViewTarget                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Udynamic_cinematic_component_bp_C::BlendCameraOut(float BlendTime, class AActor* NewViewTarget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "BlendCameraOut");

	Params::dynamic_cinematic_component_bp_C_BlendCameraOut Parms{};

	Parms.BlendTime = BlendTime;
	Parms.NewViewTarget = NewViewTarget;

	UObject::ProcessEvent(Func, &Parms);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.AllClientsComplete
// (BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::AllClientsComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "AllClientsComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.SkipCinematic
// (BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::SkipCinematic()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "SkipCinematic");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.AllClientsCompleteServerOnly
// (BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::AllClientsCompleteServerOnly()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "AllClientsCompleteServerOnly");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.AllClientsCompleteOwnerOnly
// (Net, NetReliable, NetClient, BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::AllClientsCompleteOwnerOnly()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "AllClientsCompleteOwnerOnly");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.PreloadOnClient
// (BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::PreloadOnClient()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "PreloadOnClient");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.PostSequenceUpdate
// (BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::PostSequenceUpdate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "PostSequenceUpdate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Udynamic_cinematic_component_bp_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "ReceiveTick");

	Params::dynamic_cinematic_component_bp_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.AllClientsCompleteMulticast
// (Net, NetReliable, NetMulticast, BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::AllClientsCompleteMulticast()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "AllClientsCompleteMulticast");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.EstimatedClientComplete
// (BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::EstimatedClientComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "EstimatedClientComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.SetClientCinematicState
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ECinematicPlayerState                   CinematicState                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Udynamic_cinematic_component_bp_C::SetClientCinematicState(ECinematicPlayerState CinematicState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "SetClientCinematicState");

	Params::dynamic_cinematic_component_bp_C_SetClientCinematicState Parms{};

	Parms.CinematicState = CinematicState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.FailsafeTimer
// (BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::FailsafeTimer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "FailsafeTimer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.OnSequenceEnd
// (BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::OnSequenceEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "OnSequenceEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.Reset
// (BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::Reset()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "Reset");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.PlayOnClient
// (BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::PlayOnClient()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "PlayOnClient");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.Play
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TArray<class AActor*>&            ObserverActors_0                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// const TArray<class AActor*>&            ReplacementActors_0                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// TArray<struct FReplacementActorPostCineTransform>&PostCineReplacementActorTransforms_0                   (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)

void Udynamic_cinematic_component_bp_C::Play(const TArray<class AActor*>& ObserverActors_0, const TArray<class AActor*>& ReplacementActors_0, TArray<struct FReplacementActorPostCineTransform>& PostCineReplacementActorTransforms_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "Play");

	Params::dynamic_cinematic_component_bp_C_Play Parms{};

	Parms.ObserverActors_0 = std::move(ObserverActors_0);
	Parms.ReplacementActors_0 = std::move(ReplacementActors_0);
	Parms.PostCineReplacementActorTransforms_0 = std::move(PostCineReplacementActorTransforms_0);

	UObject::ProcessEvent(Func, &Parms);

	PostCineReplacementActorTransforms_0 = std::move(Parms.PostCineReplacementActorTransforms_0);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.PreloadOnServer
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct Fdynamic_cinematic_component_preload_parameters&Parameters                                             (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void Udynamic_cinematic_component_bp_C::PreloadOnServer(const struct Fdynamic_cinematic_component_preload_parameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "PreloadOnServer");

	Params::dynamic_cinematic_component_bp_C_PreloadOnServer Parms{};

	Parms.Parameters = std::move(Parameters);

	UObject::ProcessEvent(Func, &Parms);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.SetCinematicMaterials
// (Public, BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::SetCinematicMaterials()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "SetCinematicMaterials");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.OnLoaded_EB517BEB4B2279E0CE318281E6E6C81A
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Udynamic_cinematic_component_bp_C::OnLoaded_EB517BEB4B2279E0CE318281E6E6C81A(class UClass* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "OnLoaded_EB517BEB4B2279E0CE318281E6E6C81A");

	Params::dynamic_cinematic_component_bp_C_OnLoaded_EB517BEB4B2279E0CE318281E6E6C81A Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.OnLoaded_DF9F826043B6CD0EBED950801301E3A5
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Udynamic_cinematic_component_bp_C::OnLoaded_DF9F826043B6CD0EBED950801301E3A5(class UClass* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "OnLoaded_DF9F826043B6CD0EBED950801301E3A5");

	Params::dynamic_cinematic_component_bp_C_OnLoaded_DF9F826043B6CD0EBED950801301E3A5 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.OnLoaded_4F47E7904D6F6E6C2AA1C5864FF6BE0C
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Udynamic_cinematic_component_bp_C::OnLoaded_4F47E7904D6F6E6C2AA1C5864FF6BE0C(class UClass* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "OnLoaded_4F47E7904D6F6E6C2AA1C5864FF6BE0C");

	Params::dynamic_cinematic_component_bp_C_OnLoaded_4F47E7904D6F6E6C2AA1C5864FF6BE0C Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.OnLoaded_6016B1104CD3A5F0EAABEF976B3BF735
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Udynamic_cinematic_component_bp_C::OnLoaded_6016B1104CD3A5F0EAABEF976B3BF735(class UClass* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "OnLoaded_6016B1104CD3A5F0EAABEF976B3BF735");

	Params::dynamic_cinematic_component_bp_C_OnLoaded_6016B1104CD3A5F0EAABEF976B3BF735 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.OnLoaded_2B8F0C1D48ADD10A9F747DAC0FE50811
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Udynamic_cinematic_component_bp_C::OnLoaded_2B8F0C1D48ADD10A9F747DAC0FE50811(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "OnLoaded_2B8F0C1D48ADD10A9F747DAC0FE50811");

	Params::dynamic_cinematic_component_bp_C_OnLoaded_2B8F0C1D48ADD10A9F747DAC0FE50811 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.ReplaceActorAnimSequence
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ULevelSequencePlayer*             LevelSequencePlayer                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           SequenceActor                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAnimSequenceBase*                NewAnimSequence                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Udynamic_cinematic_component_bp_C::ReplaceActorAnimSequence(class ULevelSequencePlayer* LevelSequencePlayer, class AActor* SequenceActor, class UAnimSequenceBase* NewAnimSequence)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "ReplaceActorAnimSequence");

	Params::dynamic_cinematic_component_bp_C_ReplaceActorAnimSequence Parms{};

	Parms.LevelSequencePlayer = LevelSequencePlayer;
	Parms.SequenceActor = SequenceActor;
	Parms.NewAnimSequence = NewAnimSequence;

	UObject::ProcessEvent(Func, &Parms);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.SetActorAndMeshHidden
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Hidden                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void Udynamic_cinematic_component_bp_C::SetActorAndMeshHidden(class AActor* Actor, bool Hidden)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "SetActorAndMeshHidden");

	Params::dynamic_cinematic_component_bp_C_SetActorAndMeshHidden Parms{};

	Parms.Actor = Actor;
	Parms.Hidden = Hidden;

	UObject::ProcessEvent(Func, &Parms);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.OnRep_ServerPlaybackState
// (BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::OnRep_ServerPlaybackState()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "OnRep_ServerPlaybackState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.OnRep_Clients
// (BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::OnRep_Clients()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "OnRep_Clients");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.ShouldFadeFromBlack
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Camera_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           TargetActor                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   AngleThreshold                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   DistanceThreshold                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   ShouldFade                                             (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void Udynamic_cinematic_component_bp_C::ShouldFadeFromBlack(class AActor* Camera_0, class AActor* TargetActor, float AngleThreshold, float DistanceThreshold, bool* ShouldFade)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "ShouldFadeFromBlack");

	Params::dynamic_cinematic_component_bp_C_ShouldFadeFromBlack Parms{};

	Parms.Camera_0 = Camera_0;
	Parms.TargetActor = TargetActor;
	Parms.AngleThreshold = AngleThreshold;
	Parms.DistanceThreshold = DistanceThreshold;

	UObject::ProcessEvent(Func, &Parms);

	if (ShouldFade != nullptr)
		*ShouldFade = Parms.ShouldFade;
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.FollowGround
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   GroundFollowOffset                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Smoothing                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector*                         OutGroundFollowOffset                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Udynamic_cinematic_component_bp_C::FollowGround(class AActor* Actor, const struct FVector& GroundFollowOffset, float DeltaSeconds, float Smoothing, struct FVector* OutGroundFollowOffset)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "FollowGround");

	Params::dynamic_cinematic_component_bp_C_FollowGround Parms{};

	Parms.Actor = Actor;
	Parms.GroundFollowOffset = std::move(GroundFollowOffset);
	Parms.DeltaSeconds = DeltaSeconds;
	Parms.Smoothing = Smoothing;

	UObject::ProcessEvent(Func, &Parms);

	if (OutGroundFollowOffset != nullptr)
		*OutGroundFollowOffset = std::move(Parms.OutGroundFollowOffset);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.OnRep_ReplacementActors
// (BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::OnRep_ReplacementActors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "OnRep_ReplacementActors");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.FindActorOfInterest
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Camera_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<class AActor*>&                  Actors                                                 (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// class AActor**                          BestActor                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32*                                  BestIndex                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Udynamic_cinematic_component_bp_C::FindActorOfInterest(class AActor* Camera_0, TArray<class AActor*>& Actors, class AActor** BestActor, int32* BestIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "FindActorOfInterest");

	Params::dynamic_cinematic_component_bp_C_FindActorOfInterest Parms{};

	Parms.Camera_0 = Camera_0;
	Parms.Actors = std::move(Actors);

	UObject::ProcessEvent(Func, &Parms);

	Actors = std::move(Parms.Actors);

	if (BestActor != nullptr)
		*BestActor = Parms.BestActor;

	if (BestIndex != nullptr)
		*BestIndex = Parms.BestIndex;
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.AdjustCamera
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::AdjustCamera()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "AdjustCamera");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.OnRep_PreloadParameters
// (BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::OnRep_PreloadParameters()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "OnRep_PreloadParameters");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.CalculateClientViewability
// (Public, BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::CalculateClientViewability()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "CalculateClientViewability");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.GetClientPlaybackState
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// ECinematicPlayerState*                  State                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Udynamic_cinematic_component_bp_C::GetClientPlaybackState(ECinematicPlayerState* State)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "GetClientPlaybackState");

	Params::dynamic_cinematic_component_bp_C_GetClientPlaybackState Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (State != nullptr)
		*State = Parms.State;
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.ActivateCinematicOverlay
// (Public, BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::ActivateCinematicOverlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "ActivateCinematicOverlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.DeactivateCinematicOverlay
// (Public, BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::DeactivateCinematicOverlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "DeactivateCinematicOverlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.DebugPrint
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FString&                    String                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// float                                   Duration                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Udynamic_cinematic_component_bp_C::DebugPrint(const class FString& String, float Duration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "DebugPrint");

	Params::dynamic_cinematic_component_bp_C_DebugPrint Parms{};

	Parms.String = std::move(String);
	Parms.Duration = Duration;

	UObject::ProcessEvent(Func, &Parms);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.ShowTeamDisplay
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bShow                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void Udynamic_cinematic_component_bp_C::ShowTeamDisplay(bool bShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "ShowTeamDisplay");

	Params::dynamic_cinematic_component_bp_C_ShowTeamDisplay Parms{};

	Parms.bShow = bShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.HandleReplayCineComplete
// (Public, BlueprintCallable, BlueprintEvent)

void Udynamic_cinematic_component_bp_C::HandleReplayCineComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "HandleReplayCineComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.HasComponentFinishedLoading
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool Udynamic_cinematic_component_bp_C::HasComponentFinishedLoading() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "HasComponentFinishedLoading");

	Params::dynamic_cinematic_component_bp_C_HasComponentFinishedLoading Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function dynamic_cinematic_component_bp.dynamic_cinematic_component_bp_C.BP_GetTransformOrigin
// (Event, Protected, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// struct FTransform                       ReturnValue                                            (Parm, OutParm, ReturnParm, IsPlainOldData, NoDestructor)

struct FTransform Udynamic_cinematic_component_bp_C::BP_GetTransformOrigin() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("dynamic_cinematic_component_bp_C", "BP_GetTransformOrigin");

	Params::dynamic_cinematic_component_bp_C_BP_GetTransformOrigin Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
