#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: escalation_sequence_marker_bpc

#include "Basic.hpp"

#include "escalation_sequence_marker_bpc_classes.hpp"
#include "escalation_sequence_marker_bpc_parameters.hpp"


SDK_NAMESPACE_START

// Function escalation_sequence_marker_bpc.escalation_sequence_marker_bpc_C.ExecuteUbergraph_escalation_sequence_marker_bpc
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uescalation_sequence_marker_bpc_C::ExecuteUbergraph_escalation_sequence_marker_bpc(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("escalation_sequence_marker_bpc_C", "ExecuteUbergraph_escalation_sequence_marker_bpc");

	Params::escalation_sequence_marker_bpc_C_ExecuteUbergraph_escalation_sequence_marker_bpc Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function escalation_sequence_marker_bpc.escalation_sequence_marker_bpc_C.ClientActivateAtmosphere
// (Net, NetClient, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AArchonCharacter*                 Player                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uescalation_sequence_marker_bpc_C::ClientActivateAtmosphere(class AArchonCharacter* Player)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("escalation_sequence_marker_bpc_C", "ClientActivateAtmosphere");

	Params::escalation_sequence_marker_bpc_C_ClientActivateAtmosphere Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function escalation_sequence_marker_bpc.escalation_sequence_marker_bpc_C.OnRep_next_marker
// (BlueprintCallable, BlueprintEvent)

void Uescalation_sequence_marker_bpc_C::OnRep_next_marker()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("escalation_sequence_marker_bpc_C", "OnRep_next_marker");

	UObject::ProcessEvent(Func, nullptr);
}


// Function escalation_sequence_marker_bpc.escalation_sequence_marker_bpc_C.OnRep_prev_marker
// (BlueprintCallable, BlueprintEvent)

void Uescalation_sequence_marker_bpc_C::OnRep_prev_marker()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("escalation_sequence_marker_bpc_C", "OnRep_prev_marker");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
