#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: expedition_state_bpc

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass expedition_state_bpc.expedition_state_bpc_C
// 0x0000 (0x00B0 - 0x00B0)
class Uexpedition_state_bpc_C final : public UActorComponent
{
public:
	void AuthEnableExpedition();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("expedition_state_bpc_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"expedition_state_bpc_C")
	}
	static class Uexpedition_state_bpc_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Uexpedition_state_bpc_C>();
	}
};
DUMPER7_ASSERTS_Uexpedition_state_bpc_C;

SDK_NAMESPACE_END
