#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: game_mode_helpers

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass game_mode_helpers.game_mode_helpers_C
// 0x0000 (0x0028 - 0x0028)
class Ugame_mode_helpers_C final : public UBlueprintFunctionLibrary
{
public:
	static void GetAllIslandPlayerStarts(class UObject* WorldContextObject, class FName OptionalGroupName, class UObject* __WorldContext, TArray<class APlayerStart*>* PlayerStarts);
	static void FindPlayerStartForPlayer(class APlayerState* PlayerState, class UObject* __WorldContext, class APlayerStart** PlayerStart);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("game_mode_helpers_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"game_mode_helpers_C")
	}
	static class Ugame_mode_helpers_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Ugame_mode_helpers_C>();
	}
};
DUMPER7_ASSERTS_Ugame_mode_helpers_C;

SDK_NAMESPACE_END
