#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: gatherable_item_seasonal_base_bp

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "gatherable_item_base_bp_classes.hpp"
#include "AkAudio_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass gatherable_item_seasonal_base_bp.gatherable_item_seasonal_base_bp_C
// 0x00C8 (0x0450 - 0x0388)
class Agatherable_item_seasonal_base_bp_C final : public Agatherable_item_base_bp_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_gatherable_item_seasonal_base_bp_C; // 0x0388(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UDecalComponent*                        Decal;                                             // 0x0390(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   VFXStaticMesh;                                     // 0x0398(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               VFXAtRoot;                                         // 0x03A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               SkelMeshAttachedVFX;                               // 0x03A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 GatherableSkelMesh;                                // 0x03B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAkComponent*                           AkComponent;                                       // 0x03B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               VFX;                                               // 0x03C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_0_Dissovle_1C40CF234BD20799C30418A62D1BA6C6; // 0x03C8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline_0__Direction_1C40CF234BD20799C30418A62D1BA6C6; // 0x03CC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3CD[0x3];                                      // 0x03CD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline_0;                                        // 0x03D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPlayerGatherableComponent*             PlayerGatherables;                                 // 0x03D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CityGatherableTutorialShownFlag;                   // 0x03E0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	bool                                          DesiredGatherableVisibility;                       // 0x03F0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          SeasonIdReplicated;                                // 0x03F1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3F2[0x6];                                      // 0x03F2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UAkAudioEvent*                          StartAudio;                                        // 0x03F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAkAudioEvent*                          StopAudio;                                         // 0x0400(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   ReplicatedSeasonId;                                // 0x0408(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	class UCharacterFlagComponent*                CharacterDataFlags;                                // 0x0410(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_418[0x8];                                      // 0x0418(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             SkeletalMeshTransform;                             // 0x0420(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_gatherable_item_seasonal_base_bp(int32 EntryPoint);
	void GiveGatherableRewards(class AArchonPlayerController* PlayerController);
	void OnUserCompletedInteraction(class UArchonInteractionUserComponent* User);
	void LoadAndApplySeasonAssets();
	void UpdateGatherableVisibility();
	void OnMeshSwap();
	void ReceiveBeginPlay();
	void OnLoaded_F78F643A4EED1B6630FCBB9973C3C1F9(class UObject* Loaded);
	void OnLoaded_4566E972485EE4C27564DC9931D351DE(class UObject* Loaded);
	void OnLoaded_1563F5C84E5B34A211440C9F9926C903(class UObject* Loaded);
	void OnLoaded_EF2D440F4209FDE350EB34BEE39A98BE(class UObject* Loaded);
	void OnLoaded_ECD0D09743BF7286E325B2B014B8DEC5(class UObject* Loaded);
	void OnLoaded_2446B09A4674AF025A5E1BB678C9092F(class UObject* Loaded);
	void OnLoaded_66B8B5B047B5FA1486141FB80670ED8E(class UObject* Loaded);
	void OnLoaded_312386E04D3F9D1F0E77EC9D4ABC3C0D(class UObject* Loaded);
	void OnLoaded_0E4F43A34E474D267C19BF9B1245350E(class UObject* Loaded);
	void OnLoaded_DE3BFE3440300541038CFAA6193E715D(class UObject* Loaded);
	void Timeline_0__DeactivateParticle__EventFunc();
	void Timeline_0__UpdateFunc();
	void Timeline_0__FinishedFunc();
	void UserConstructionScript();
	void CanUserStartInteraction_(class UArchonInteractionUserComponent* User, bool* CanUse);
	bool SetGatherableVisible(bool IsVisible);
	void OnRep_ReplicatedSeasonId();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("gatherable_item_seasonal_base_bp_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"gatherable_item_seasonal_base_bp_C")
	}
	static class Agatherable_item_seasonal_base_bp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Agatherable_item_seasonal_base_bp_C>();
	}
};
DUMPER7_ASSERTS_Agatherable_item_seasonal_base_bp_C;

SDK_NAMESPACE_END
