#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: gliding_input_bpc

#include "Basic.hpp"

#include "Archon_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass gliding_input_bpc.gliding_input_bpc_C
// 0x0008 (0x0168 - 0x0160)
class Ugliding_input_bpc_C final : public UArchonInputComponent
{
public:
	class UArchonGlidingComponent*                GlidingBPC;                                        // 0x0160(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("gliding_input_bpc_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"gliding_input_bpc_C")
	}
	static class Ugliding_input_bpc_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Ugliding_input_bpc_C>();
	}
};
DUMPER7_ASSERTS_Ugliding_input_bpc_C;

SDK_NAMESPACE_END
