#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: hit_reaction_bpc

#include "Basic.hpp"

#include "hit_reaction_bpc_classes.hpp"
#include "hit_reaction_bpc_parameters.hpp"


SDK_NAMESPACE_START

// Function hit_reaction_bpc.hit_reaction_bpc_C.ExecuteUbergraph_hit_reaction_bpc
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uhit_reaction_bpc_C::ExecuteUbergraph_hit_reaction_bpc(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hit_reaction_bpc_C", "ExecuteUbergraph_hit_reaction_bpc");

	Params::hit_reaction_bpc_C_ExecuteUbergraph_hit_reaction_bpc Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function hit_reaction_bpc.hit_reaction_bpc_C.CancelActiveStagger
// (BlueprintCallable, BlueprintEvent)

void Uhit_reaction_bpc_C::CancelActiveStagger()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hit_reaction_bpc_C", "CancelActiveStagger");

	UObject::ProcessEvent(Func, nullptr);
}


// Function hit_reaction_bpc.hit_reaction_bpc_C.BP_OnStaggerActionStarted
// (Event, Protected, BlueprintEvent)
// Parameters:
// float                                   DamageMagnitude                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uhit_reaction_bpc_C::BP_OnStaggerActionStarted(float DamageMagnitude)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hit_reaction_bpc_C", "BP_OnStaggerActionStarted");

	Params::hit_reaction_bpc_C_BP_OnStaggerActionStarted Parms{};

	Parms.DamageMagnitude = DamageMagnitude;

	UObject::ProcessEvent(Func, &Parms);
}


// Function hit_reaction_bpc.hit_reaction_bpc_C.BP_OnStaggerActionFinished
// (Event, Protected, BlueprintEvent)

void Uhit_reaction_bpc_C::BP_OnStaggerActionFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hit_reaction_bpc_C", "BP_OnStaggerActionFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function hit_reaction_bpc.hit_reaction_bpc_C.On Enter Bleedout
// (BlueprintCallable, BlueprintEvent)

void Uhit_reaction_bpc_C::On_Enter_Bleedout()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hit_reaction_bpc_C", "On Enter Bleedout");

	UObject::ProcessEvent(Func, nullptr);
}


// Function hit_reaction_bpc.hit_reaction_bpc_C.Play Hit Reaction
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FHitReactionTableEntry&    Hit_Reaction_Entry                                     (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
// const struct FVector&                   Impact_Direction                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const float&                            DamageMagnitude                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uhit_reaction_bpc_C::Play_Hit_Reaction(const struct FHitReactionTableEntry& Hit_Reaction_Entry, const struct FVector& Impact_Direction, const float& DamageMagnitude)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hit_reaction_bpc_C", "Play Hit Reaction");

	Params::hit_reaction_bpc_C_Play_Hit_Reaction Parms{};

	Parms.Hit_Reaction_Entry = std::move(Hit_Reaction_Entry);
	Parms.Impact_Direction = std::move(Impact_Direction);
	Parms.DamageMagnitude = DamageMagnitude;

	UObject::ProcessEvent(Func, &Parms);
}


// Function hit_reaction_bpc.hit_reaction_bpc_C.On Received Hit
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Source                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FArchonHitEventParams&     Params_0                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)

void Uhit_reaction_bpc_C::On_Received_Hit(class AActor* Source, const struct FArchonHitEventParams& Params_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hit_reaction_bpc_C", "On Received Hit");

	Params::hit_reaction_bpc_C_On_Received_Hit Parms{};

	Parms.Source = Source;
	Parms.Params_0 = std::move(Params_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function hit_reaction_bpc.hit_reaction_bpc_C.ReceiveEndPlay
// (Event, Public, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uhit_reaction_bpc_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hit_reaction_bpc_C", "ReceiveEndPlay");

	Params::hit_reaction_bpc_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function hit_reaction_bpc.hit_reaction_bpc_C.Client_HandleForceFeedback
// (Net, NetClient, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Victim                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UForceFeedbackEffect*             FeedbackEffect                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uhit_reaction_bpc_C::Client_HandleForceFeedback(class AActor* Victim, class UForceFeedbackEffect* FeedbackEffect)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hit_reaction_bpc_C", "Client_HandleForceFeedback");

	Params::hit_reaction_bpc_C_Client_HandleForceFeedback Parms{};

	Parms.Victim = Victim;
	Parms.FeedbackEffect = FeedbackEffect;

	UObject::ProcessEvent(Func, &Parms);
}


// Function hit_reaction_bpc.hit_reaction_bpc_C.Client_DebugInfo
// (Net, NetClient, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           InstigatorActor_0                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   Hit_Direction                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EVictimRelativeHitDirection             Hit_Direction_Enum                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Attacker_Angle                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EVictimRelativeHitDirection             Attacker_Direction                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uhit_reaction_bpc_C::Client_DebugInfo(class AActor* InstigatorActor_0, const struct FVector& Hit_Direction, EVictimRelativeHitDirection Hit_Direction_Enum, float Attacker_Angle, EVictimRelativeHitDirection Attacker_Direction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hit_reaction_bpc_C", "Client_DebugInfo");

	Params::hit_reaction_bpc_C_Client_DebugInfo Parms{};

	Parms.InstigatorActor_0 = InstigatorActor_0;
	Parms.Hit_Direction = std::move(Hit_Direction);
	Parms.Hit_Direction_Enum = Hit_Direction_Enum;
	Parms.Attacker_Angle = Attacker_Angle;
	Parms.Attacker_Direction = Attacker_Direction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function hit_reaction_bpc.hit_reaction_bpc_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void Uhit_reaction_bpc_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hit_reaction_bpc_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function hit_reaction_bpc.hit_reaction_bpc_C.OnEndOperation
// (BlueprintCallable, BlueprintEvent)

void Uhit_reaction_bpc_C::OnEndOperation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hit_reaction_bpc_C", "OnEndOperation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function hit_reaction_bpc.hit_reaction_bpc_C.OnDamageReceived
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTagContainer&     InstigatorTags_0                                       (BlueprintVisible, BlueprintReadOnly, Parm)
// class UObject*                          Source_Object                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   Hit_Direction                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           InstigatorActor_0                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Magnitude                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uhit_reaction_bpc_C::OnDamageReceived(const struct FGameplayTagContainer& InstigatorTags_0, class UObject* Source_Object, const struct FVector& Hit_Direction, class AActor* InstigatorActor_0, float Magnitude)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hit_reaction_bpc_C", "OnDamageReceived");

	Params::hit_reaction_bpc_C_OnDamageReceived Parms{};

	Parms.InstigatorTags_0 = std::move(InstigatorTags_0);
	Parms.Source_Object = Source_Object;
	Parms.Hit_Direction = std::move(Hit_Direction);
	Parms.InstigatorActor_0 = InstigatorActor_0;
	Parms.Magnitude = Magnitude;

	UObject::ProcessEvent(Func, &Parms);
}


// Function hit_reaction_bpc.hit_reaction_bpc_C.Get Matching Hit Reaction
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FHitReactionTableEntry>&  HitReactionTable_0                                     (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference, HasGetValueTypeHash)
// const struct FGameplayTagContainer&     Filter_By                                              (BlueprintVisible, BlueprintReadOnly, Parm)
// const struct FGameplayTagContainer&     Instigator_Tags                                        (BlueprintVisible, BlueprintReadOnly, Parm)
// EVictimRelativeHitDirection             Attacker_Direction                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EVictimRelativeHitDirection             Impact_Direction                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FHitReactionTableEntry*          MatchingEntry                                          (Parm, OutParm, ContainsInstancedReference)
// bool*                                   Success                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void Uhit_reaction_bpc_C::Get_Matching_Hit_Reaction(TArray<struct FHitReactionTableEntry>& HitReactionTable_0, const struct FGameplayTagContainer& Filter_By, const struct FGameplayTagContainer& Instigator_Tags, EVictimRelativeHitDirection Attacker_Direction, EVictimRelativeHitDirection Impact_Direction, struct FHitReactionTableEntry* MatchingEntry, bool* Success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hit_reaction_bpc_C", "Get Matching Hit Reaction");

	Params::hit_reaction_bpc_C_Get_Matching_Hit_Reaction Parms{};

	Parms.HitReactionTable_0 = std::move(HitReactionTable_0);
	Parms.Filter_By = std::move(Filter_By);
	Parms.Instigator_Tags = std::move(Instigator_Tags);
	Parms.Attacker_Direction = Attacker_Direction;
	Parms.Impact_Direction = Impact_Direction;

	UObject::ProcessEvent(Func, &Parms);

	HitReactionTable_0 = std::move(Parms.HitReactionTable_0);

	if (MatchingEntry != nullptr)
		*MatchingEntry = std::move(Parms.MatchingEntry);

	if (Success != nullptr)
		*Success = Parms.Success;
}


// Function hit_reaction_bpc.hit_reaction_bpc_C.FilterGameplayTagContainer
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTagContainer&     InstigatorTags_0                                       (BlueprintVisible, BlueprintReadOnly, Parm)
// const struct FGameplayTagContainer&     Filter_By                                              (BlueprintVisible, BlueprintReadOnly, Parm)
// bool                                    DebugPrint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FGameplayTagContainer*           FilteredTags                                           (Parm, OutParm)

void Uhit_reaction_bpc_C::FilterGameplayTagContainer(const struct FGameplayTagContainer& InstigatorTags_0, const struct FGameplayTagContainer& Filter_By, bool DebugPrint, struct FGameplayTagContainer* FilteredTags)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hit_reaction_bpc_C", "FilterGameplayTagContainer");

	Params::hit_reaction_bpc_C_FilterGameplayTagContainer Parms{};

	Parms.InstigatorTags_0 = std::move(InstigatorTags_0);
	Parms.Filter_By = std::move(Filter_By);
	Parms.DebugPrint = DebugPrint;

	UObject::ProcessEvent(Func, &Parms);

	if (FilteredTags != nullptr)
		*FilteredTags = std::move(Parms.FilteredTags);
}


// Function hit_reaction_bpc.hit_reaction_bpc_C.GetAttackerDirection
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class AActor*                           InstigatorActor_0                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           TargetActor                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EVictimRelativeHitDirection*            AttackerDirection                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float*                                  AttackerAngle                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uhit_reaction_bpc_C::GetAttackerDirection(class AActor* InstigatorActor_0, class AActor* TargetActor, EVictimRelativeHitDirection* AttackerDirection, float* AttackerAngle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hit_reaction_bpc_C", "GetAttackerDirection");

	Params::hit_reaction_bpc_C_GetAttackerDirection Parms{};

	Parms.InstigatorActor_0 = InstigatorActor_0;
	Parms.TargetActor = TargetActor;

	UObject::ProcessEvent(Func, &Parms);

	if (AttackerDirection != nullptr)
		*AttackerDirection = Parms.AttackerDirection;

	if (AttackerAngle != nullptr)
		*AttackerAngle = Parms.AttackerAngle;
}


// Function hit_reaction_bpc.hit_reaction_bpc_C.ConvertAngleToDirection
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   Angle                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EVictimRelativeHitDirection*            Direction                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uhit_reaction_bpc_C::ConvertAngleToDirection(float Angle, EVictimRelativeHitDirection* Direction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hit_reaction_bpc_C", "ConvertAngleToDirection");

	Params::hit_reaction_bpc_C_ConvertAngleToDirection Parms{};

	Parms.Angle = Angle;

	UObject::ProcessEvent(Func, &Parms);

	if (Direction != nullptr)
		*Direction = Parms.Direction;
}


// Function hit_reaction_bpc.hit_reaction_bpc_C.DebugInfo
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           InstigatorActor_0                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   Hit_Direction                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EVictimRelativeHitDirection             Hit_Direction_Enum                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Attacker_Angle                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EVictimRelativeHitDirection             Attacker_Direction_Enum                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uhit_reaction_bpc_C::DebugInfo(class AActor* InstigatorActor_0, const struct FVector& Hit_Direction, EVictimRelativeHitDirection Hit_Direction_Enum, float Attacker_Angle, EVictimRelativeHitDirection Attacker_Direction_Enum)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hit_reaction_bpc_C", "DebugInfo");

	Params::hit_reaction_bpc_C_DebugInfo Parms{};

	Parms.InstigatorActor_0 = InstigatorActor_0;
	Parms.Hit_Direction = std::move(Hit_Direction);
	Parms.Hit_Direction_Enum = Hit_Direction_Enum;
	Parms.Attacker_Angle = Attacker_Angle;
	Parms.Attacker_Direction_Enum = Attacker_Direction_Enum;

	UObject::ProcessEvent(Func, &Parms);
}


// Function hit_reaction_bpc.hit_reaction_bpc_C.Debug Print Hit Reaction Entry Info
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FHitReactionTableEntry&    HitReactionEntry                                       (BlueprintVisible, BlueprintReadOnly, Parm, ContainsInstancedReference)

void Uhit_reaction_bpc_C::Debug_Print_Hit_Reaction_Entry_Info(const struct FHitReactionTableEntry& HitReactionEntry)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hit_reaction_bpc_C", "Debug Print Hit Reaction Entry Info");

	Params::hit_reaction_bpc_C_Debug_Print_Hit_Reaction_Entry_Info Parms{};

	Parms.HitReactionEntry = std::move(HitReactionEntry);

	UObject::ProcessEvent(Func, &Parms);
}


// Function hit_reaction_bpc.hit_reaction_bpc_C.HandleForceFeedbackDamage
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Victim                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UForceFeedbackEffect*             FeedbackEffect                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uhit_reaction_bpc_C::HandleForceFeedbackDamage(class AActor* Victim, class UForceFeedbackEffect* FeedbackEffect)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hit_reaction_bpc_C", "HandleForceFeedbackDamage");

	Params::hit_reaction_bpc_C_HandleForceFeedbackDamage Parms{};

	Parms.Victim = Victim;
	Parms.FeedbackEffect = FeedbackEffect;

	UObject::ProcessEvent(Func, &Parms);
}


// Function hit_reaction_bpc.hit_reaction_bpc_C.SanityCheck_PlzReadCommentInFunction
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// EVictimRelativeHitDirection             ImpactDirection                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EVictimRelativeHitDirection             AttackerDirection                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   ActorForwardVector                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   NegatedHitDirection                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Angle                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EVictimRelativeHitDirection*            Output                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uhit_reaction_bpc_C::SanityCheck_PlzReadCommentInFunction(EVictimRelativeHitDirection ImpactDirection, EVictimRelativeHitDirection AttackerDirection, const struct FVector& ActorForwardVector, const struct FVector& NegatedHitDirection, float Angle, EVictimRelativeHitDirection* Output)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hit_reaction_bpc_C", "SanityCheck_PlzReadCommentInFunction");

	Params::hit_reaction_bpc_C_SanityCheck_PlzReadCommentInFunction Parms{};

	Parms.ImpactDirection = ImpactDirection;
	Parms.AttackerDirection = AttackerDirection;
	Parms.ActorForwardVector = std::move(ActorForwardVector);
	Parms.NegatedHitDirection = std::move(NegatedHitDirection);
	Parms.Angle = Angle;

	UObject::ProcessEvent(Func, &Parms);

	if (Output != nullptr)
		*Output = Parms.Output;
}


// Function hit_reaction_bpc.hit_reaction_bpc_C.AlignHitReactionDirectionToImpactDirection
// (Public, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// const struct FVector&                   Impact_Direction                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EVictimRelativeHitDirection             Hit_Reaction_Direction                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uhit_reaction_bpc_C::AlignHitReactionDirectionToImpactDirection(const struct FVector& Impact_Direction, EVictimRelativeHitDirection Hit_Reaction_Direction) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hit_reaction_bpc_C", "AlignHitReactionDirectionToImpactDirection");

	Params::hit_reaction_bpc_C_AlignHitReactionDirectionToImpactDirection Parms{};

	Parms.Impact_Direction = std::move(Impact_Direction);
	Parms.Hit_Reaction_Direction = Hit_Reaction_Direction;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
