#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: hud_inputkey_bpw

#include "Basic.hpp"

#include "Archon_structs.hpp"
#include "Archon_classes.hpp"
#include "Engine_structs.hpp"
#include "InputCore_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass hud_inputkey_bpw.hud_inputkey_bpw_C
// 0x0048 (0x0370 - 0x0328)
class Uhud_inputkey_bpw_C final : public UHUDInputKey
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0328(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Backpiece;                                         // 0x0330(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Icon;                                              // 0x0338(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_Button;                                    // 0x0340(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             txt;                                               // 0x0348(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FKey                                   Key;                                               // 0x0350(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn, HasGetValueTypeHash)
	int32                                         SizeOverride;                                      // 0x0368(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	EDebugPlatformOverride                        DesignerPlatformOverride;                          // 0x036C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ShouldSwapVirtualIcons;                            // 0x036D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_hud_inputkey_bpw(int32 EntryPoint);
	void UpdateKey(const struct FKey& MappedKey);
	void Setup_Empty_Key();
	void Preview_For_Platform(EDebugPlatformOverride PlatformOverride);
	void Setup_Key(const struct FKeyInfo& KeyInfo, bool ShowLabel);
	void PreConstruct(bool IsDesignTime);
	void Refresh();
	void Construct();
	void OnLoaded_267A00A8405FB467C655939B7F184EF5(class UObject* Loaded);
	void UpdateSize();
	void SetSwapVirtualIconSwap(bool bShouldSwap);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("hud_inputkey_bpw_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"hud_inputkey_bpw_C")
	}
	static class Uhud_inputkey_bpw_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Uhud_inputkey_bpw_C>();
	}
};
DUMPER7_ASSERTS_Uhud_inputkey_bpw_C;

SDK_NAMESPACE_END
