#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: hunt_info_page_bpw

#include "Basic.hpp"

#include "hunt_info_page_bpw_classes.hpp"
#include "hunt_info_page_bpw_parameters.hpp"


SDK_NAMESPACE_START

// Function hunt_info_page_bpw.hunt_info_page_bpw_C.ExecuteUbergraph_hunt_info_page_bpw
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uhunt_info_page_bpw_C::ExecuteUbergraph_hunt_info_page_bpw(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hunt_info_page_bpw_C", "ExecuteUbergraph_hunt_info_page_bpw");

	Params::hunt_info_page_bpw_C_ExecuteUbergraph_hunt_info_page_bpw Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function hunt_info_page_bpw.hunt_info_page_bpw_C.OnLoadoutUpdated
// (Event, Protected, BlueprintEvent)

void Uhunt_info_page_bpw_C::OnLoadoutUpdated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hunt_info_page_bpw_C", "OnLoadoutUpdated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function hunt_info_page_bpw.hunt_info_page_bpw_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void Uhunt_info_page_bpw_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hunt_info_page_bpw_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function hunt_info_page_bpw.hunt_info_page_bpw_C.Update Current Loadout Info
// (BlueprintCallable, BlueprintEvent)

void Uhunt_info_page_bpw_C::Update_Current_Loadout_Info()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hunt_info_page_bpw_C", "Update Current Loadout Info");

	UObject::ProcessEvent(Func, nullptr);
}


// Function hunt_info_page_bpw.hunt_info_page_bpw_C.OnViewModelUpdated
// (Event, Protected, BlueprintEvent)

void Uhunt_info_page_bpw_C::OnViewModelUpdated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hunt_info_page_bpw_C", "OnViewModelUpdated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function hunt_info_page_bpw.hunt_info_page_bpw_C.OnLoaded_267A00A8405FB467C655939B8815E88F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uhunt_info_page_bpw_C::OnLoaded_267A00A8405FB467C655939B8815E88F(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("hunt_info_page_bpw_C", "OnLoaded_267A00A8405FB467C655939B8815E88F");

	Params::hunt_info_page_bpw_C_OnLoaded_267A00A8405FB467C655939B8815E88F Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
