#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: huntpass_prestige_store_bps

#include "Basic.hpp"

#include "huntpass_prestige_store_bps_classes.hpp"
#include "huntpass_prestige_store_bps_parameters.hpp"


SDK_NAMESPACE_START

// Function huntpass_prestige_store_bps.huntpass_prestige_store_bps_C.ExecuteUbergraph_huntpass_prestige_store_bps
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uhuntpass_prestige_store_bps_C::ExecuteUbergraph_huntpass_prestige_store_bps(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("huntpass_prestige_store_bps_C", "ExecuteUbergraph_huntpass_prestige_store_bps");

	Params::huntpass_prestige_store_bps_C_ExecuteUbergraph_huntpass_prestige_store_bps Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function huntpass_prestige_store_bps.huntpass_prestige_store_bps_C.OnViewPortResizedEvent
// (Event, Protected, BlueprintEvent)
// Parameters:
// const struct FIntPoint&                 Size                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uhuntpass_prestige_store_bps_C::OnViewPortResizedEvent(const struct FIntPoint& Size)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("huntpass_prestige_store_bps_C", "OnViewPortResizedEvent");

	Params::huntpass_prestige_store_bps_C_OnViewPortResizedEvent Parms{};

	Parms.Size = std::move(Size);

	UObject::ProcessEvent(Func, &Parms);
}


// Function huntpass_prestige_store_bps.huntpass_prestige_store_bps_C.OnStoreItemsUpdated
// (Event, Protected, BlueprintEvent)

void Uhuntpass_prestige_store_bps_C::OnStoreItemsUpdated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("huntpass_prestige_store_bps_C", "OnStoreItemsUpdated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function huntpass_prestige_store_bps.huntpass_prestige_store_bps_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void Uhuntpass_prestige_store_bps_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("huntpass_prestige_store_bps_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function huntpass_prestige_store_bps.huntpass_prestige_store_bps_C.OnShowStoreItemDetailWidget
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bShowed                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void Uhuntpass_prestige_store_bps_C::OnShowStoreItemDetailWidget(bool bShowed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("huntpass_prestige_store_bps_C", "OnShowStoreItemDetailWidget");

	Params::huntpass_prestige_store_bps_C_OnShowStoreItemDetailWidget Parms{};

	Parms.bShowed = bShowed;

	UObject::ProcessEvent(Func, &Parms);
}


// Function huntpass_prestige_store_bps.huntpass_prestige_store_bps_C.OnUpdatedStoreItem
// (Event, Protected, BlueprintEvent)

void Uhuntpass_prestige_store_bps_C::OnUpdatedStoreItem()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("huntpass_prestige_store_bps_C", "OnUpdatedStoreItem");

	UObject::ProcessEvent(Func, nullptr);
}


// Function huntpass_prestige_store_bps.huntpass_prestige_store_bps_C.OnScreenHideBeginEvent
// (Event, Protected, BlueprintEvent)

void Uhuntpass_prestige_store_bps_C::OnScreenHideBeginEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("huntpass_prestige_store_bps_C", "OnScreenHideBeginEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function huntpass_prestige_store_bps.huntpass_prestige_store_bps_C.Get_DescriptionTextBlock_Text
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText Uhuntpass_prestige_store_bps_C::Get_DescriptionTextBlock_Text()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("huntpass_prestige_store_bps_C", "Get_DescriptionTextBlock_Text");

	Params::huntpass_prestige_store_bps_C_Get_DescriptionTextBlock_Text Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function huntpass_prestige_store_bps.huntpass_prestige_store_bps_C.UpdateLegendButton
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    DetailItemShowed                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void Uhuntpass_prestige_store_bps_C::UpdateLegendButton(bool DetailItemShowed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("huntpass_prestige_store_bps_C", "UpdateLegendButton");

	Params::huntpass_prestige_store_bps_C_UpdateLegendButton Parms{};

	Parms.DetailItemShowed = DetailItemShowed;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
