#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: hunt_quest_monitor_bpc

#include "Basic.hpp"

#include "Archon_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "LocalizationFramework_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass hunt_quest_monitor_bpc.hunt_quest_monitor_bpc_C
// 0x00A8 (0x0158 - 0x00B0)
class Uhunt_quest_monitor_bpc_C final : public UActorComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<class UQuestEventData*>                LQuestEventQueue;                                  // 0x00B8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class UQuest*                                 LCurrentQuest;                                     // 0x00C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class Uquest_event_dialogue2_bp_C*            LActiveDialogueEvent;                              // 0x00D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class Ulantern_radio_prototype_bpw_C*         LHuntDialogueWidget;                               // 0x00D8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DisplayTextDuration;                               // 0x00E0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          EnableDebug;                                       // 0x00E4(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E5[0x3];                                       // 0x00E5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         EvaulationPeriod;                                  // 0x00E8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_EC[0x4];                                       // 0x00EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           TextDisplayTimerHandle;                            // 0x00F0(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class Uquest_event_audio_bp_C*                LActiveAudioEvent;                                 // 0x00F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class Uquest_event_widget_bp_C*               LActiveWidgetEvent;                                // 0x0100(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bEventsEnabled;                                    // 0x0108(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_109[0x7];                                      // 0x0109(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           LUpdateTimer;                                      // 0x0110(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          bPaused;                                           // 0x0118(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_119[0x7];                                      // 0x0119(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UQuestEventData*                        LQuestEvent;                                       // 0x0120(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UArchonDialogManagerComponent*          CachedDialogManager;                               // 0x0128(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   LSubtitle;                                         // 0x0130(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UTutorialComponent*                     CachedTutorialComponent;                           // 0x0148(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          EnableQueueDebug;                                  // 0x0150(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_hunt_quest_monitor_bpc(int32 EntryPoint);
	void StartTimer();
	void UnpauseQuestMonitorComponent();
	void PauseQuestMonitorComponent();
	void UpdateQuests();
	void ReceiveTick(float DeltaSeconds);
	void ReceiveBeginPlay();
	void DisplayDebugInfo();
	void GetSpeaker(class UArchonSpeaker** Speaker);
	void MuteQuestMonitorComponent(bool* OutEnabled);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("hunt_quest_monitor_bpc_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"hunt_quest_monitor_bpc_C")
	}
	static class Uhunt_quest_monitor_bpc_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Uhunt_quest_monitor_bpc_C>();
	}
};
DUMPER7_ASSERTS_Uhunt_quest_monitor_bpc_C;

SDK_NAMESPACE_END
