#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: huntpass_prestige_purchase_button_bpw

#include "Basic.hpp"

#include "huntpass_prestige_purchase_button_bpw_classes.hpp"
#include "huntpass_prestige_purchase_button_bpw_parameters.hpp"


SDK_NAMESPACE_START

// Function huntpass_prestige_purchase_button_bpw.huntpass_prestige_purchase_button_bpw_C.ExecuteUbergraph_huntpass_prestige_purchase_button_bpw
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uhuntpass_prestige_purchase_button_bpw_C::ExecuteUbergraph_huntpass_prestige_purchase_button_bpw(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("huntpass_prestige_purchase_button_bpw_C", "ExecuteUbergraph_huntpass_prestige_purchase_button_bpw");

	Params::huntpass_prestige_purchase_button_bpw_C_ExecuteUbergraph_huntpass_prestige_purchase_button_bpw Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function huntpass_prestige_purchase_button_bpw.huntpass_prestige_purchase_button_bpw_C.OnUpdateLoopAnimations
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsButtonEnable                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void Uhuntpass_prestige_purchase_button_bpw_C::OnUpdateLoopAnimations(bool bIsButtonEnable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("huntpass_prestige_purchase_button_bpw_C", "OnUpdateLoopAnimations");

	Params::huntpass_prestige_purchase_button_bpw_C_OnUpdateLoopAnimations Parms{};

	Parms.bIsButtonEnable = bIsButtonEnable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function huntpass_prestige_purchase_button_bpw.huntpass_prestige_purchase_button_bpw_C.BndEvt__ActualButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void Uhuntpass_prestige_purchase_button_bpw_C::BndEvt__ActualButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("huntpass_prestige_purchase_button_bpw_C", "BndEvt__ActualButton_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function huntpass_prestige_purchase_button_bpw.huntpass_prestige_purchase_button_bpw_C.BndEvt__ActualButton_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void Uhuntpass_prestige_purchase_button_bpw_C::BndEvt__ActualButton_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("huntpass_prestige_purchase_button_bpw_C", "BndEvt__ActualButton_K2Node_ComponentBoundEvent_0_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function huntpass_prestige_purchase_button_bpw.huntpass_prestige_purchase_button_bpw_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void Uhuntpass_prestige_purchase_button_bpw_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("huntpass_prestige_purchase_button_bpw_C", "PreConstruct");

	Params::huntpass_prestige_purchase_button_bpw_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function huntpass_prestige_purchase_button_bpw.huntpass_prestige_purchase_button_bpw_C.LoadIcon
// (BlueprintCallable, BlueprintEvent)

void Uhuntpass_prestige_purchase_button_bpw_C::LoadIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("huntpass_prestige_purchase_button_bpw_C", "LoadIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function huntpass_prestige_purchase_button_bpw.huntpass_prestige_purchase_button_bpw_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void Uhuntpass_prestige_purchase_button_bpw_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("huntpass_prestige_purchase_button_bpw_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function huntpass_prestige_purchase_button_bpw.huntpass_prestige_purchase_button_bpw_C.OnFocusReceived
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply Uhuntpass_prestige_purchase_button_bpw_C::OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("huntpass_prestige_purchase_button_bpw_C", "OnFocusReceived");

	Params::huntpass_prestige_purchase_button_bpw_C_OnFocusReceived Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
