#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: inherit_stat_type

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum inherit_stat_type.inherit_stat_type
// NumValues: 0x0003
enum class Einherit_stat_type : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	inherit_stat_MAX                         = 2,
};

SDK_NAMESPACE_END
