#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: input_key_function_library

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass input_key_function_library.input_key_function_library_C
// 0x0000 (0x0028 - 0x0028)
class Uinput_key_function_library_C final : public UBlueprintFunctionLibrary
{
public:
	static void GetInputKeyDisplayName(const struct FKey& Key, class UObject* __WorldContext, class FText* Display_Name);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("input_key_function_library_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"input_key_function_library_C")
	}
	static class Uinput_key_function_library_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Uinput_key_function_library_C>();
	}
};
DUMPER7_ASSERTS_Uinput_key_function_library_C;

SDK_NAMESPACE_END
