#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: kite_bp

#include "Basic.hpp"

#include "AkAudio_structs.hpp"
#include "PlaneBounds_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Archon_classes.hpp"
#include "Engine_structs.hpp"
#include "kite_struct_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass kite_bp.kite_bp_C
// 0x01C0 (0x0410 - 0x0250)
class Akite_bp_C final : public AArchonSkyfishingKite
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0250(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USkeletalMeshComponent*                 KiteSkeletalMesh;                                  // 0x0258(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCameraComponent*                       CameraReelingGameLocator;                          // 0x0260(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCameraComponent*                       Camera;                                            // 0x0268(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0270(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         KiteFlyToLocation_alpha_15EB846A46409E3FC28F9A9AF85E2245; // 0x0278(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            KiteFlyToLocation__Direction_15EB846A46409E3FC28F9A9AF85E2245; // 0x027C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_27D[0x3];                                      // 0x027D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     KiteFlyToLocation;                                 // 0x0280(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              KiteReachedTarget;                                 // 0x0288(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	uint8                                         Pad_298[0x8];                                      // 0x0298(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             StartTransform;                                    // 0x02A0(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	struct FTransform                             TargetTransform;                                   // 0x02D0(0x0030)(Edit, BlueprintVisible, Net, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor)
	struct FVector2D                              Velocity;                                          // 0x0300(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              TargetVelocity;                                    // 0x0308(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              OldVelocity;                                       // 0x0310(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              Location2D;                                        // 0x0318(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         BaseAccelerationRate;                              // 0x0320(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_324[0x4];                                      // 0x0324(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class Askyfish_cloud_bp_C*                    CloudRef;                                          // 0x0328(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsMovingKite;                                      // 0x0330(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_331[0x3];                                      // 0x0331(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPlaneBounds                           SkyfishesPlaneBounds;                              // 0x0334(0x0030)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FPlaneBounds                           KitePlaneBounds;                                   // 0x0364(0x0030)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CatchDistance;                                     // 0x0394(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class Uskyfisher_bpc_C*                       SkyfisherRef;                                      // 0x0398(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	struct Fkite_struct                           KiteStats;                                         // 0x03A0(0x0058)(Edit, BlueprintVisible, Net, RepNotify, ExposeOnSpawn, HasGetValueTypeHash)
	float                                         WindResistanceMod;                                 // 0x03F8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         ManeuverabilityMod;                                // 0x03FC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              Location2DChangeThisTick;                          // 0x0400(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_kite_bp(int32 EntryPoint);
	void ClientSetPlaneBounds(const struct FPlaneBounds& InKiteBounds);
	void AuthSetPlaneBounds(const struct FPlaneBounds& InKiteBounds);
	void ReceiveTick(float DeltaSeconds);
	void ChangeTargetVelocity(const struct FVector2D& InNewVelocity);
	void ReceiveBeginPlay();
	void FlyToTarget();
	void AuthFlyToTarget(const struct FTransform& InTargetTransform);
	void KiteFlyToLocation__UpdateFunc();
	void KiteFlyToLocation__FinishedFunc();
	void OnRep_TargetTransform();
	void GetKiteVector(const struct FVector2D& InPoint, struct FVector* OutVector);
	void UpdateVelocity();
	void AccelerateVelocityToTarget(float InCurrentVelocity, float InTargetVelocity, float InAcceleration, float* OutNewVelocity);
	void UpdatePosition(float InTimeDelta);
	void StartKiteFlyingMinigame(const struct FPlaneBounds& InKitePlaneBounds);
	void SetupKiteStats();
	void OnRep_KiteStats();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("kite_bp_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"kite_bp_C")
	}
	static class Akite_bp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Akite_bp_C>();
	}
};
DUMPER7_ASSERTS_Akite_bp_C;

SDK_NAMESPACE_END
