#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: lightweight_keybind_bpw

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "InputCore_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass lightweight_keybind_bpw.lightweight_keybind_bpw_C
// 0x0050 (0x0328 - 0x02D8)
class Ulightweight_keybind_bpw_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UOverlay*                               IconKeybind;                                       // 0x02E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_KeyName;                                 // 0x02E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         TextKeybind;                                       // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class Uw_inputkey_bpw_C*                      w_inputkey_bpw;                                    // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        WidgetSwitcher_0;                                  // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FKey                                   Key;                                               // 0x0308(0x0018)(Edit, BlueprintVisible, HasGetValueTypeHash)
	bool                                          RefreshInFlight;                                   // 0x0320(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_lightweight_keybind_bpw(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void UpdateKey(const struct FKey& Key_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("lightweight_keybind_bpw_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"lightweight_keybind_bpw_C")
	}
	static class Ulightweight_keybind_bpw_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Ulightweight_keybind_bpw_C>();
	}
};
DUMPER7_ASSERTS_Ulightweight_keybind_bpw_C;

SDK_NAMESPACE_END
