#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: linked_slayer_bpc

#include "Basic.hpp"

#include "Archon_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass linked_slayer_bpc.linked_slayer_bpc_C
// 0x0000 (0x0158 - 0x0158)
class Ulinked_slayer_bpc_C final : public ULinkedSlayerComponent
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("linked_slayer_bpc_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"linked_slayer_bpc_C")
	}
	static class Ulinked_slayer_bpc_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Ulinked_slayer_bpc_C>();
	}
};
DUMPER7_ASSERTS_Ulinked_slayer_bpc_C;

SDK_NAMESPACE_END
