#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: lockoncam_input_bpc

#include "Basic.hpp"

#include "InputCore_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function lockoncam_input_bpc.lockoncam_input_bpc_C.ExecuteUbergraph_lockoncam_input_bpc
// 0x0040 (0x0040 - 0x0000)
struct lockoncam_input_bpc_C_ExecuteUbergraph_lockoncam_input_bpc final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FKey                                   K2Node_CustomEvent_Key_1;                          // 0x0008(0x0018)(ConstParm, HasGetValueTypeHash)
	struct FKey                                   K2Node_CustomEvent_Key;                            // 0x0020(0x0018)(HasGetValueTypeHash)
	bool                                          CallFunc_Key_IsGamepadKey_ReturnValue;             // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Key_IsGamepadKey_ReturnValue_1;           // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_lockoncam_input_bpc_C_ExecuteUbergraph_lockoncam_input_bpc;

// Function lockoncam_input_bpc.lockoncam_input_bpc_C.HandleToggleSheathePressed
// 0x0018 (0x0018 - 0x0000)
struct lockoncam_input_bpc_C_HandleToggleSheathePressed final
{
public:
	struct FKey                                   Key;                                               // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_lockoncam_input_bpc_C_HandleToggleSheathePressed;

// Function lockoncam_input_bpc.lockoncam_input_bpc_C.HandleResetCameraPressed
// 0x0018 (0x0018 - 0x0000)
struct lockoncam_input_bpc_C_HandleResetCameraPressed final
{
public:
	struct FKey                                   Key;                                               // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_lockoncam_input_bpc_C_HandleResetCameraPressed;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
