#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: loot_condition_type

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum loot_condition_type.loot_condition_type
// NumValues: 0x0004
enum class Eloot_condition_type : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	loot_condition_MAX                       = 3,
};

SDK_NAMESPACE_END
