#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MapScreen_bpw

#include "Basic.hpp"

#include "MapScreen_bpw_classes.hpp"
#include "MapScreen_bpw_parameters.hpp"


SDK_NAMESPACE_START

// Function MapScreen_bpw.MapScreen_bpw_C.ExecuteUbergraph_MapScreen_bpw
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMapScreen_bpw_C::ExecuteUbergraph_MapScreen_bpw(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapScreen_bpw_C", "ExecuteUbergraph_MapScreen_bpw");

	Params::MapScreen_bpw_C_ExecuteUbergraph_MapScreen_bpw Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function MapScreen_bpw.MapScreen_bpw_C.OnScreenHideBeginEvent
// (Event, Protected, BlueprintEvent)

void UMapScreen_bpw_C::OnScreenHideBeginEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapScreen_bpw_C", "OnScreenHideBeginEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapScreen_bpw.MapScreen_bpw_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UMapScreen_bpw_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapScreen_bpw_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapScreen_bpw.MapScreen_bpw_C.OnHuntStart
// (Event, Protected, BlueprintEvent)

void UMapScreen_bpw_C::OnHuntStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapScreen_bpw_C", "OnHuntStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapScreen_bpw.MapScreen_bpw_C.OnViewPortResizedEvent
// (Event, Protected, BlueprintEvent)
// Parameters:
// const struct FIntPoint&                 Size                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMapScreen_bpw_C::OnViewPortResizedEvent(const struct FIntPoint& Size)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapScreen_bpw_C", "OnViewPortResizedEvent");

	Params::MapScreen_bpw_C_OnViewPortResizedEvent Parms{};

	Parms.Size = std::move(Size);

	UObject::ProcessEvent(Func, &Parms);
}


// Function MapScreen_bpw.MapScreen_bpw_C.OnStartHuntVisible
// (Event, Protected, BlueprintEvent)

void UMapScreen_bpw_C::OnStartHuntVisible()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapScreen_bpw_C", "OnStartHuntVisible");

	UObject::ProcessEvent(Func, nullptr);
}


// Function MapScreen_bpw.MapScreen_bpw_C.OnMenuBack
// (Event, Protected, BlueprintEvent)

void UMapScreen_bpw_C::OnMenuBack()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("MapScreen_bpw_C", "OnMenuBack");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
