#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: mastery_bpc

#include "Basic.hpp"

#include "Archon_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass mastery_bpc.mastery_bpc_C
// 0x0000 (0x0348 - 0x0348)
class Umastery_bpc_C final : public UMasteryComponent
{
public:
	int32 GetBehemothMasteryXPReward(class AArchonBehemoth* Behemoth);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("mastery_bpc_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"mastery_bpc_C")
	}
	static class Umastery_bpc_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Umastery_bpc_C>();
	}
};
DUMPER7_ASSERTS_Umastery_bpc_C;

SDK_NAMESPACE_END
