#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: max_danger_averted_bpw

#include "Basic.hpp"

#include "max_danger_averted_bpw_classes.hpp"
#include "max_danger_averted_bpw_parameters.hpp"


SDK_NAMESPACE_START

// Function max_danger_averted_bpw.max_danger_averted_bpw_C.ExecuteUbergraph_max_danger_averted_bpw
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Umax_danger_averted_bpw_C::ExecuteUbergraph_max_danger_averted_bpw(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("max_danger_averted_bpw_C", "ExecuteUbergraph_max_danger_averted_bpw");

	Params::max_danger_averted_bpw_C_ExecuteUbergraph_max_danger_averted_bpw Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function max_danger_averted_bpw.max_danger_averted_bpw_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void Umax_danger_averted_bpw_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("max_danger_averted_bpw_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function max_danger_averted_bpw.max_danger_averted_bpw_C.Get_Crew Lives Remaining_Text_0
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class FText                             ReturnValue                                            (Parm, OutParm, ReturnParm)

class FText Umax_danger_averted_bpw_C::Get_Crew_Lives_Remaining_Text_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("max_danger_averted_bpw_C", "Get_Crew Lives Remaining_Text_0");

	Params::max_danger_averted_bpw_C_Get_Crew_Lives_Remaining_Text_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
