#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: paperdoll_scene_bpc

#include "Basic.hpp"

#include "Archon_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass paperdoll_scene_bpc.paperdoll_scene_bpc_C
// 0x0030 (0x0158 - 0x0128)
class Upaperdoll_scene_bpc_C final : public UPaperDollSceneComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0128(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class Aatmosphere_spawner_bp_C*               AtmosphereSpawner;                                 // 0x0130(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         skylight_intensity;                                // 0x0138(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         directional_light_intensity;                       // 0x013C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTextureCube*                           Cubemap;                                           // 0x0140(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Cubemap_Intensity;                                 // 0x0148(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         min_brightness;                                    // 0x014C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         max_brightness;                                    // 0x0150(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_paperdoll_scene_bpc(int32 EntryPoint);
	void OnHide(bool bShowAtmospehere);
	void OnShow(bool bHideAtmosphere);
	void ReceiveBeginPlay();
	void SetAtmosphere(bool ShowPaperdoll);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("paperdoll_scene_bpc_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"paperdoll_scene_bpc_C")
	}
	static class Upaperdoll_scene_bpc_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Upaperdoll_scene_bpc_C>();
	}
};
DUMPER7_ASSERTS_Upaperdoll_scene_bpc_C;

SDK_NAMESPACE_END
