#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: part_stage_material_info

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct part_stage_material_info.part_stage_material_info
// 0x0014 (0x0014 - 0x0000)
struct Fpart_stage_material_info final
{
public:
	class FName                                   MaterialParamName_2_2A5715954A8B93FFED403E9DC28733DF; // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MaterialTargetValue_5_E8C1781E49A23785B590ACAFD29C7692; // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         MaterialInterpSpeed_12_0D1F8FDB4C2CF45B1F09698DFECBF39B; // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         INTERNAL_CurrentValue_11_0381730640B636ABD5338097856D16AE; // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Fpart_stage_material_info;

SDK_NAMESPACE_END
