#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: play_montage_bpo

#include "Basic.hpp"

#include "play_montage_bpo_classes.hpp"
#include "play_montage_bpo_parameters.hpp"


SDK_NAMESPACE_START

// Function play_montage_bpo.play_montage_bpo_C.ExecuteUbergraph_play_montage_bpo
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uplay_montage_bpo_C::ExecuteUbergraph_play_montage_bpo(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("play_montage_bpo_C", "ExecuteUbergraph_play_montage_bpo");

	Params::play_montage_bpo_C_ExecuteUbergraph_play_montage_bpo Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function play_montage_bpo.play_montage_bpo_C.OnTick
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FArchonGameplayOperationTickArgs&Args                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void Uplay_montage_bpo_C::OnTick(const struct FArchonGameplayOperationTickArgs& Args)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("play_montage_bpo_C", "OnTick");

	Params::play_montage_bpo_C_OnTick Parms{};

	Parms.Args = std::move(Args);

	UObject::ProcessEvent(Func, &Parms);
}


// Function play_montage_bpo.play_montage_bpo_C.OnMontageBlendingOut_Event_0
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAnimMontage*                     Montage_0                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bInterrupted                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void Uplay_montage_bpo_C::OnMontageBlendingOut_Event_0(class UAnimMontage* Montage_0, bool bInterrupted)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("play_montage_bpo_C", "OnMontageBlendingOut_Event_0");

	Params::play_montage_bpo_C_OnMontageBlendingOut_Event_0 Parms{};

	Parms.Montage_0 = Montage_0;
	Parms.bInterrupted = bInterrupted;

	UObject::ProcessEvent(Func, &Parms);
}


// Function play_montage_bpo.play_montage_bpo_C.OnStart
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FArchonGameplayOperationArgs&Args                                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void Uplay_montage_bpo_C::OnStart(const struct FArchonGameplayOperationArgs& Args)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("play_montage_bpo_C", "OnStart");

	Params::play_montage_bpo_C_OnStart Parms{};

	Parms.Args = std::move(Args);

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
