#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: progression_award_bpw

#include "Basic.hpp"

#include "progression_rank_table_row_structs.hpp"
#include "Engine_structs.hpp"
#include "progression_award_structs.hpp"
#include "UMG_classes.hpp"
#include "AkAudio_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass progression_award_bpw.progression_award_bpw_C
// 0x0110 (0x03E8 - 0x02D8)
class Uprogression_award_bpw_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       FadeOut;                                           // 0x02E0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       RankUp;                                            // 0x02E8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UScrollBox*                             BoostContainer;                                    // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCanvasPanel*                           ProgressBarPanel;                                  // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 RankUpFlash;                                       // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_PrevRankNum;                             // 0x0308(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_Rank;                                    // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_RankNum;                                 // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FName                                   Track;                                             // 0x0320(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class Uprogression_event_bpw_C*>       EventBarAnimations;                                // 0x0328(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference, HasGetValueTypeHash)
	struct Fprogression_award                     Grant;                                             // 0x0338(0x0038)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(const struct Fprogression_award& Award)> AnimationsFinished;       // 0x0370(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	int32                                         CurrentRankNum;                                    // 0x0380(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_384[0x4];                                      // 0x0384(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct Fprogression_rank_table_row            LocalTrackDataRow;                                 // 0x0388(0x0058)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	class Uprogression_bpc_C*                     ProgressionComponent;                              // 0x03E0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_progression_award_bpw(int32 EntryPoint);
	void ReceivedPatronBoostPlayers(TArray<class FString>& PatronBoostPlayers);
	void OnAnimationFinished(const class UWidgetAnimation* Animation);
	void Bar_Animation_Finished(const struct Fprogression_event& Event);
	void Construct();
	void Set_Rank_Number(class UTextBlock* Target, int32 Number);
	void Setup_Events(const struct Fprogression_award& Grant_0, float* Duration);
	void Add_Bar_Animation_to_Panel(class UWidget* BarAnimation);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("progression_award_bpw_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"progression_award_bpw_C")
	}
	static class Uprogression_award_bpw_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Uprogression_award_bpw_C>();
	}
};
DUMPER7_ASSERTS_Uprogression_award_bpw_C;

SDK_NAMESPACE_END
