#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: projectile_base_bp

#include "Basic.hpp"

#include "Archon_structs.hpp"
#include "Archon_classes.hpp"
#include "Engine_structs.hpp"
#include "projectile_homing_type_structs.hpp"
#include "archon_impulse_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "conditional_damage_row_structs.hpp"
#include "projectile_movement_type_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass projectile_base_bp.projectile_base_bp_C
// 0x01B8 (0x0600 - 0x0448)
class Aprojectile_base_bp_C : public AArchonProjectileBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0448(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UAkComponent*                           Ak;                                                // 0x0450(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UParticleSystemComponent*               ParticleSystem;                                    // 0x0458(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCapsuleComponent*                      Colliding_Body;                                    // 0x0460(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UProjectileMovementComponent*           ProjectileMovement;                                // 0x0468(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         ExplodeOnTerrainDecalFadeTimeline_Fadeout_1B39E2174052A01EEE0E66ADC3D27576; // 0x0470(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            ExplodeOnTerrainDecalFadeTimeline__Direction_1B39E2174052A01EEE0E66ADC3D27576; // 0x0474(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_475[0x3];                                      // 0x0475(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     ExplodeOnTerrainDecalFadeTimeline;                 // 0x0478(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  OwningPawn;                                        // 0x0480(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	class FName                                   DamageKey;                                         // 0x0488(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	float                                         Vertical_Height_Offset;                            // 0x0490(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Max_Distance_Before_Fall;                          // 0x0494(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Vertical_Fall_Rate;                                // 0x0498(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Use_Fall_Rate;                                     // 0x049C(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          SharedDamageGUID;                                  // 0x049D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	uint8                                         Pad_49E[0x2];                                      // 0x049E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGuid                                  DamageGUID;                                        // 0x04A0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	float                                         FloatModifier;                                     // 0x04B0(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          DisableParticleOnExplode;                          // 0x04B4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4B5[0x3];                                      // 0x04B5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         ExplodeDelayOnTerrain;                             // 0x04B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4BC[0x4];                                      // 0x04BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct Farchon_impulse>                ImpulsesToSpawnOnStop;                             // 0x04C0(0x0010)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TArray<struct Farchon_impulse>                ImpulsesToSpawnOnExplode;                          // 0x04D0(0x0010)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TArray<struct Farchon_impulse>                ImpulsesToSpawnOnHit;                              // 0x04E0(0x0010)(Edit, BlueprintVisible, HasGetValueTypeHash)
	TArray<struct Farchon_impulse>                ImpulsesToSpawnOnStart;                            // 0x04F0(0x0010)(Edit, BlueprintVisible, HasGetValueTypeHash)
	bool                                          DisableCollisionOnStop;                            // 0x0500(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_501[0x7];                                      // 0x0501(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UClass*>                         BuffsToApplyOnHit;                                 // 0x0508(0x0010)(Edit, BlueprintVisible, HasGetValueTypeHash)
	Eprojectile_movement_type                     ProjectileMovementType;                            // 0x0518(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_519[0x3];                                      // 0x0519(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                LobbedProjectileTarget;                            // 0x051C(0x000C)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         L_EstimatedTimeToGround;                           // 0x0528(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         L_EstimatedTimeToTarget;                           // 0x052C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         OptionalEQSSpawnTimeOffset;                        // 0x0530(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	Eprojectile_homing_type                       HomingType;                                        // 0x0534(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_535[0x3];                                      // 0x0535(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         DamageActivationDelay;                             // 0x0538(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         MaxNumberOfHits;                                   // 0x053C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         HitCooldown;                                       // 0x0540(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         L_LastHitTime;                                     // 0x0544(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         L_NumHits;                                         // 0x0548(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         OptionalProjectileIndex;                           // 0x054C(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          L_StopAllMovement;                                 // 0x0550(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          DebugDrawStartPosition;                            // 0x0551(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          DebugDrawPath;                                     // 0x0552(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_553[0x1];                                      // 0x0553(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CustomProjectileDamageScale;                       // 0x0554(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          DebugProjectile;                                   // 0x0558(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_559[0x7];                                      // 0x0559(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 L_SweepedHitActor;                                 // 0x0560(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CollisionSweepCollisionProfileNames;               // 0x0568(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class Aprojectile_base_bp_C* Projectile)> OnProjectileExploded;    // 0x0570(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class Aprojectile_base_bp_C* Projectile)> OnProjectileStopped_Dispatcher; // 0x0580(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TArray<struct Fconditional_damage_row>        AdditionalDamageRows;                              // 0x0590(0x0010)(Edit, BlueprintVisible, Net, DisableEditOnInstance, HasGetValueTypeHash)
	bool                                          BuffOnHitCanApplyToSelf;                           // 0x05A0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5A1[0x3];                                      // 0x05A1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Snap_to_Ground_Offset;                             // 0x05A4(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsLocalPlayerAudioEnabled;                         // 0x05A8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          CanGainMeterLifestealAndLanternByDamagingThis;     // 0x05A9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5AA[0x2];                                      // 0x05AA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         TogglePitch;                                       // 0x05AC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         BehemothVsBehemothDamageScale;                     // 0x05B0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5B4[0x4];                                      // 0x05B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           ExplodeDelayOnTerrainTimer;                        // 0x05B8(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FVector                                L_ExplosionLoc;                                    // 0x05C0(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5CC[0x4];                                      // 0x05CC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInterface*                     ExplodeOnTerrainDecal;                             // 0x05D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                ExplodeOnTerrainDecalSize;                         // 0x05D8(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               ExplodeOnTerrainDecalRotation;                     // 0x05E4(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	float                                         ExplodeOnTerrainDecalLifeSpan;                     // 0x05F0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         ExplodeOnTerrainDecalFadeoutTime;                  // 0x05F4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               ExplodeOnTerrainDecalMaterialRef;                  // 0x05F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_projectile_base_bp(int32 EntryPoint);
	void DelayedExpireEvent();
	void EndPlayFromPool(EEndPlayReason EndPlayReason);
	void BeginPlayFromPool();
	void ExplodeDelayOnTerrainComplete();
	void ProjectileExploded(const struct FVector& ExplosionLocation, EProjectileExplodeType ExplodeType);
	void AuthOnProjectileDamageOverlap(class AActor* OtherActor, class UPrimitiveComponent* OtherComponent, const struct FHitResult& SweepResult);
	void TargetIsInvulnerable(class AActor* AbilityActor, const struct FGameplayTagContainer& InvulnerabilityTags);
	void OnProjectileExploded_DelegateCall_BP();
	void SpawnImpulsesOnExplode(EProjectileExplodeType ExplodeType);
	void StopImpulsesAtEnd();
	void SpawnImpulsesOnBeginPlay();
	void AudioIsSetLocal_BP();
	void AuthCreateDamageGUID();
	void AuthSweepHitEvent();
	void Multi_ProjectileStopped();
	void Multi_Hit();
	void Multi_Explode(const struct FVector& HitLocation, const struct FVector& HitNormal, EProjectileExplodeType ExplodeType);
	void DebugMulticastDrawProjectileSphere(const struct FVector& Location, float Duration, float Thickness, const struct FLinearColor& Color);
	void SpawnedActor_Cleanup();
	void OnProjectileStopped();
	void BndEvt__ProjectileMovement_K2Node_ComponentBoundEvent_0_OnProjectileStopDelegate__DelegateSignature(const struct FHitResult& ImpactResult);
	void MulticastVelocity(const struct FVector& NewVelocity);
	void CalculateHoming(float DeltaSeconds);
	void MulticastVelocityAndGravityChanges(const struct FVector& NewVel, float NewGravity);
	void HandleHit_Server(class AActor* Damager, class AActor* DamagedActor, const struct FArchonCombatHitParams& Params_0);
	void ClearLockOnCameraTarget();
	void SetCameraLockOnTargetSocket(class FName TargetSocket);
	void SetProjectileMovementType(Eprojectile_movement_type NewMovementType);
	void HandleHit_Client(class AActor* Damager, class AActor* DamagedActor, const struct FArchonCombatHitParams& Params_0, bool bHitWouldHaveSucceededOnServer);
	void ExplodeOnTerrainDecalFadeTimeline__UpdateFunc();
	void ExplodeOnTerrainDecalFadeTimeline__FinishedFunc();
	void UserConstructionScript();
	void Server___Apply_Damage(class AActor* Target_Actor, const struct FHitResult& Hit_Info, class UPrimitiveComponent* OtherComponent);
	void AuthBecomeLobbedProjectile(const struct FVector& TargetPos, float MinDistanceForScaling, float MaxDistanceForScaling, float PeakHeightAtMinDistance, float PeakHeightAtMaxDistance, float LateralSpeedAtMinDistance, float LateralSpeedAtMaxDistance);
	void AudioSetIsLocal();
	void CalculateDamageRow(class AActor* TargetActor, struct FDamageTableData* FinalDamageRow, float* DamageScale, bool* Succeeded);
	void GetDamageTags(const struct FDamageTableData& DamageTableData, TArray<struct FGameplayTag>* Tags_0);
	void UpdateDrivenProjectileLocationAndRotation(float DeltaTime);
	void UpdateParticlePosition_BP(float DeltaSeconds, class AActor* Actor, struct FVector* OutputPosition, struct FRotator* OutputRotation);
	void InvulnerableTarget(class AActor* InputPin, const struct FGameplayTagContainer& InvulnerabilityTags);
	uint8 CanHitThisTarget(class AActor* TargetActor);
	void InitializePoolable(const struct FTransform& SpawnTransform, ESpawnActorCollisionHandlingMethod CollisionHandlingOverride, class AActor* Owner_0, class APawn* OwningPawn_0, class FName DamageKey_0, bool SharedDamageGUID_0, const struct FGuid& DamageGUID_0, float FloatModifier_0, float OptionalEQSSpawnTimeOffset_0, int32 OptionalProjectileIndex_0, class AActor* HomingTarget_0, class APawn* OwningPawnNative, class FName SharedDamageGUIDName_0, class APawn* Instigator_0);
	void ResetProjectileMovementComponent();
	void CanDamageThisTarget(class AActor* OtherActor, class UPrimitiveComponent* OtherComponent, bool* Can);
	void CanExplodeOnThisTarget(class AActor* OtherActor, class UPrimitiveComponent* OtherComponent, bool* Can);
	void GetLookAtAlpha(float* LookAtAlpha);
	void GetLookAtVector(struct FVector* LookAtVector);
	void GetDefaultElementalAttackType(EArchonElementType* DefaultElementalAttackType);
	void CanHitCBPushPullTarget(class UPrimitiveComponent* ComponentHit, bool* Hits_);
	void GetMeterGainScale(float* Scale);
	void AllowBeamToPierce(struct FHitResult& Hit, bool* Pierce_);
	void ShouldPlayMonsterHitSounds(bool* ShouldPlayMonsterHitSounds_0);
	void GetLockOnSockets(TArray<class FName>* SocketNames);
	void UpdateParticlePosition(float DeltaSeconds, class Aprojectile_base_bp_C* ProjectileActor, struct FVector* Position, struct FRotator* Rotation);

	void GetFallbackProjectileSpawnOffset(struct FVector* Offset) const;
	void GetMesh(class USkeletalMeshComponent** SkeletalMesh) const;
	void IgnoreEQSCharacterCapsuleAdjust(bool* IgnoreEQSCharacterCapsuleAdjust_0) const;
	void CanGainMeterLifestealAndLanternFromHittingThis(bool* CanGainTheseEffects) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("projectile_base_bp_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"projectile_base_bp_C")
	}
	static class Aprojectile_base_bp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Aprojectile_base_bp_C>();
	}
};
DUMPER7_ASSERTS_Aprojectile_base_bp_C;

SDK_NAMESPACE_END
