#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: quest_logic_bpc

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "quest_button_input_types_enum_structs.hpp"
#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass quest_logic_bpc.quest_logic_bpc_C
// 0x00E0 (0x0190 - 0x00B0)
class Uquest_logic_bpc_C final : public UActorComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<class AActor*>                         LActiveVolumes;                                    // 0x00B8(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance, HasGetValueTypeHash)
	float                                         BehemothFleeTime;                                  // 0x00C8(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         WispGatherTime;                                    // 0x00CC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TMap<class FString, float>                    ConditionTimerMap;                                 // 0x00D0(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	TMap<Equest_button_input_types_enum, float>   InputLastPressedTimeMap;                           // 0x0120(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FRotator                               LPreviousViewRotation;                             // 0x0170(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	float                                         CameraPitchThreshold;                              // 0x017C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CameraYawThreshold;                                // 0x0180(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bIsTutorialHuntActive;                             // 0x0184(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor)
	uint8                                         Pad_185[0x3];                                      // 0x0185(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         PlayerHitCount;                                    // 0x0188(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_quest_logic_bpc(int32 EntryPoint);
	void BehemothFlee();
	void SetWispPickupTime(float Time);
	void ReceiveBeginPlay();
	void OnPlayerTakeDamage(class AActor* DamagedActor, float Damage, const class UDamageType* DamageType, class AController* InstigatedBy, class AActor* DamageCauser);
	void StartInputMonitorTimer();
	void ActorGameplayStart();
	void OnOverlap(class AActor* OverlappedActor, class AActor* OtherActor);
	void CheckButtonInput();
	void StartConditionTimer(const class FString& ConditionGUID);
	void GetConditionTimerValue(const class FString& ConditionID, float* TimerValue, bool* IsValid);
	void ClearConditionTimer(const class FString& ConditionGUID);
	void SetInputLastRecordedTime(Equest_button_input_types_enum Input);
	void OnRep_bIsTutorialIsland();

	void GetInputLastRecordedTime(Equest_button_input_types_enum Input, float* LastRecordedTime) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("quest_logic_bpc_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"quest_logic_bpc_C")
	}
	static class Uquest_logic_bpc_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Uquest_logic_bpc_C>();
	}
};
DUMPER7_ASSERTS_Uquest_logic_bpc_C;

SDK_NAMESPACE_END
