#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: quest_button_input_types_enum

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum quest_button_input_types_enum.quest_button_input_types_enum
// NumValues: 0x0009
enum class Equest_button_input_types_enum : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	NewEnumerator4                           = 4,
	NewEnumerator5                           = 5,
	NewEnumerator6                           = 6,
	NewEnumerator7                           = 7,
	quest_button_input_types_MAX             = 8,
};

SDK_NAMESPACE_END
