#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QuickChatScreen_bps

#include "Basic.hpp"

#include "Archon_classes.hpp"
#include "Engine_structs.hpp"
#include "AkAudio_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass QuickChatScreen_bps.QuickChatScreen_bps_C
// 0x0010 (0x0458 - 0x0448)
class UQuickChatScreen_bps_C final : public UQuickChatScreen
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0448(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_65;                                          // 0x0450(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_QuickChatScreen_bps(int32 EntryPoint);
	void OnModeChanged();
	void OnScreenHideBeginEvent();
	void Construct();
	class UWidget* GetDefaultFocusedWidget();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("QuickChatScreen_bps_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"QuickChatScreen_bps_C")
	}
	static class UQuickChatScreen_bps_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UQuickChatScreen_bps_C>();
	}
};
DUMPER7_ASSERTS_UQuickChatScreen_bps_C;

SDK_NAMESPACE_END
