#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: QuickChatRadialMenu_bpw

#include "Basic.hpp"

#include "Archon_classes.hpp"
#include "Engine_structs.hpp"
#include "UMG_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass QuickChatRadialMenu_bpw.QuickChatRadialMenu_bpw_C
// 0x0008 (0x0420 - 0x0418)
class UQuickChatRadialMenu_bpw_C final : public UQuickChatRadialMenu
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0418(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_QuickChatRadialMenu_bpw(int32 EntryPoint);
	void BndEvt__RadialMenu_K2Node_ComponentBoundEvent_0_OnRadialMenuCursurVisibility__DelegateSignature(bool bVisible, float CancelingPercent);
	class UWidget* GetDefaultFocusedWidget();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("QuickChatRadialMenu_bpw_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"QuickChatRadialMenu_bpw_C")
	}
	static class UQuickChatRadialMenu_bpw_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UQuickChatRadialMenu_bpw_C>();
	}
};
DUMPER7_ASSERTS_UQuickChatRadialMenu_bpw_C;

SDK_NAMESPACE_END
