#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RadialMenu_bpw

#include "Basic.hpp"

#include "Archon_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass RadialMenu_bpw.RadialMenu_bpw_C
// 0x0010 (0x0440 - 0x0430)
class URadialMenu_bpw_C final : public UArchonRadialMenu
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0430(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_45;                                          // 0x0438(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_RadialMenu_bpw(int32 EntryPoint);
	void OnItemSelected(int32 ItemIndex);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("RadialMenu_bpw_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RadialMenu_bpw_C")
	}
	static class URadialMenu_bpw_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URadialMenu_bpw_C>();
	}
};
DUMPER7_ASSERTS_URadialMenu_bpw_C;

SDK_NAMESPACE_END
