#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: rejoin_session_unavailable_popup_bpw

#include "Basic.hpp"

#include "Archon_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass rejoin_session_unavailable_popup_bpw.rejoin_session_unavailable_popup_bpw_C
// 0x0028 (0x0478 - 0x0450)
class Urejoin_session_unavailable_popup_bpw_C final : public UArchonPopup
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0450(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Intro;                                             // 0x0458(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 BackgroundTitle;                                   // 0x0460(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_2;                                           // 0x0468(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_98;                                          // 0x0470(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_rejoin_session_unavailable_popup_bpw(int32 EntryPoint);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("rejoin_session_unavailable_popup_bpw_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"rejoin_session_unavailable_popup_bpw_C")
	}
	static class Urejoin_session_unavailable_popup_bpw_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Urejoin_session_unavailable_popup_bpw_C>();
	}
};
DUMPER7_ASSERTS_Urejoin_session_unavailable_popup_bpw_C;

SDK_NAMESPACE_END
