#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RemoteSession

#include "Basic.hpp"

#include "MediaIOCore_classes.hpp"


SDK_NAMESPACE_START

// Class RemoteSession.RemoteSessionMediaOutput
// 0x0010 (0x0040 - 0x0030)
class URemoteSessionMediaOutput final : public UMediaOutput
{
public:
	uint8                                         Pad_30[0x10];                                      // 0x0030(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("RemoteSessionMediaOutput")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RemoteSessionMediaOutput")
	}
	static class URemoteSessionMediaOutput* GetDefaultObj()
	{
		return GetDefaultObjImpl<URemoteSessionMediaOutput>();
	}
};
DUMPER7_ASSERTS_URemoteSessionMediaOutput;

// Class RemoteSession.RemoteSessionMediaCapture
// 0x0010 (0x0118 - 0x0108)
class URemoteSessionMediaCapture final : public UMediaCapture
{
public:
	uint8                                         Pad_108[0x10];                                     // 0x0108(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("RemoteSessionMediaCapture")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"RemoteSessionMediaCapture")
	}
	static class URemoteSessionMediaCapture* GetDefaultObj()
	{
		return GetDefaultObjImpl<URemoteSessionMediaCapture>();
	}
};
DUMPER7_ASSERTS_URemoteSessionMediaCapture;

SDK_NAMESPACE_END
