#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: skyfisher1_default

#include "Basic.hpp"

#include "skyfisher1_default_classes.hpp"
#include "skyfisher1_default_parameters.hpp"


SDK_NAMESPACE_START

// Function skyfisher1_default.skyfisher1_default_C.ExecuteUbergraph_skyfisher1_default
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uskyfisher1_default_C::ExecuteUbergraph_skyfisher1_default(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("skyfisher1_default_C", "ExecuteUbergraph_skyfisher1_default");

	Params::skyfisher1_default_C_ExecuteUbergraph_skyfisher1_default Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function skyfisher1_default.skyfisher1_default_C.BP_OnEnter
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FOnEnterParams&            EnterParams                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor)

void Uskyfisher1_default_C::BP_OnEnter(const struct FOnEnterParams& EnterParams)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("skyfisher1_default_C", "BP_OnEnter");

	Params::skyfisher1_default_C_BP_OnEnter Parms{};

	Parms.EnterParams = std::move(EnterParams);

	UObject::ProcessEvent(Func, &Parms);
}


// Function skyfisher1_default.skyfisher1_default_C.BP_EvaluateTransitionToDestStates
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FOnTransitionParams&       TransitionParams                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor)
// class UArchonActivityStateNode*         ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UArchonActivityStateNode* Uskyfisher1_default_C::BP_EvaluateTransitionToDestStates(const struct FOnTransitionParams& TransitionParams)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("skyfisher1_default_C", "BP_EvaluateTransitionToDestStates");

	Params::skyfisher1_default_C_BP_EvaluateTransitionToDestStates Parms{};

	Parms.TransitionParams = std::move(TransitionParams);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
