#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: skyfish_velocity_source_interface

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function skyfish_velocity_source_interface.skyfish_velocity_source_interface_C.GetCurrentVelocity
// 0x0008 (0x0008 - 0x0000)
struct skyfish_velocity_source_interface_C_GetCurrentVelocity final
{
public:
	struct FVector2D                              OutCurrentVelocity;                                // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_skyfish_velocity_source_interface_C_GetCurrentVelocity;

// Function skyfish_velocity_source_interface.skyfish_velocity_source_interface_C.GetSourceName
// 0x0010 (0x0010 - 0x0000)
struct skyfish_velocity_source_interface_C_GetSourceName final
{
public:
	class FString                                 OutText;                                           // 0x0000(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_skyfish_velocity_source_interface_C_GetSourceName;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
