#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: skyfish_label_bpw

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass skyfish_label_bpw.skyfish_label_bpw_C
// 0x0028 (0x0300 - 0x02D8)
class Uskyfish_label_bpw_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             Label_Text;                                        // 0x02E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   TextLabel;                                         // 0x02E8(0x0018)(Edit, BlueprintVisible, Net, RepNotify, ExposeOnSpawn)

public:
	void ExecuteUbergraph_skyfish_label_bpw(int32 EntryPoint);
	void Construct();
	void OnRep_TextLabel();
	void UpdateText();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("skyfish_label_bpw_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"skyfish_label_bpw_C")
	}
	static class Uskyfish_label_bpw_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Uskyfish_label_bpw_C>();
	}
};
DUMPER7_ASSERTS_Uskyfish_label_bpw_C;

SDK_NAMESPACE_END
