#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: staggerable_bpc

#include "Basic.hpp"

#include "stagger_armor_data_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "stagger_stage_structs.hpp"
#include "final_stagger_stage_strategy_structs.hpp"
#include "stagger_telemetry_data_structs.hpp"
#include "stagger_type_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass staggerable_bpc.staggerable_bpc_C
// 0x00A0 (0x0150 - 0x00B0)
class Ustaggerable_bpc_C final : public UActorComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<struct Fstagger_stage>                 StaggerData;                                       // 0x00B8(0x0010)(Edit, BlueprintVisible, Net, HasGetValueTypeHash)
	float                                         PerPlayerScaling;                                  // 0x00C8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CurrentStaggerHealth;                              // 0x00CC(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CurrentStaggerStage;                               // 0x00D0(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Efinal_stagger_stage_strategy                 FinalStageStrategy;                                // 0x00D4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          FinishedStaggerStages;                             // 0x00D5(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          DebugStaggers;                                     // 0x00D6(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D7[0x1];                                       // 0x00D7(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CurrentStaggerMaxHealth;                           // 0x00D8(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Debug1HitStagger;                                  // 0x00DC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_DD[0x3];                                       // 0x00DD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct Fstagger_telemetry_data>        StaggerTelemetryData;                              // 0x00E0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	float                                         StaggerArmorDuration;                              // 0x00F0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CloseToStaggerEffectsActive;                       // 0x00F4(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor)
	uint8                                         Pad_F5[0x3];                                       // 0x00F5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystemComponent*               AlmostStaggeredVFX;                                // 0x00F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct Fstagger_stage>                 BaseStaggerData;                                   // 0x0100(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	TArray<struct Fstagger_armor_data>            StaggerArmorStack;                                 // 0x0110(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)
	int32                                         L_armorIndex;                                      // 0x0120(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         ArmorScalingFactor;                                // 0x0124(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TotalArmorValueForUI;                              // 0x0128(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TotalInitialArmorValueForUI;                       // 0x012C(0x0004)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class Astagger_behemoth_telegraph_bp_C*       StaggerVFX;                                        // 0x0130(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                VFX_Offset;                                        // 0x0138(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   Staggerable_VFX_Socket;                            // 0x0144(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_staggerable_bpc(int32 EntryPoint);
	void ShowStaggerVFX();
	void HideStaggerVFX();
	void RefreshStaggerEffectsActive();
	void DegenStaggerArmor();
	void MulticastTelemetryData(const TArray<struct Fstagger_telemetry_data>& StaggerTelemetryData_0);
	void AuthSendStaggerTelemetryData();
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);
	void TryAddStaggerDamage(float TotalBaseStaggerDamage, class AActor* Instigator, float PostCalcStaggerMultiplier, float BaseDamageStaggerMultiplier, float PerHitStaggerBonus, float StaggerResistPenetrationPercent, class UMonsterPartComponent* StaggeredPart, const struct FGameplayTagContainer& StaggerAttackDamageEventTags, bool* StaggerCausedByThisDamage, float* StaggerDamageDealt);
	void GetCurrentStaggerData(struct Fstagger_stage* StaggerData_0);
	void CanReceiveStaggerDamage(bool* Staggerable);
	void ChangeStaggerStage(bool DoStagger, int32 NewStaggerStage, class UMonsterPartComponent* StaggeredPart, Estagger_type StaggerType, class AActor* StaggerCauser, const struct FGameplayTagContainer& StaggerAttackDamageEventTags);
	void RecordStaggerDamage(class AActor* Instigator, float StaggerDamage, bool CausedAStagger);
	void GetIndexOfStaggerData(class AActor* Instigator, int32* Index_0);
	void OnRep_CloseToStaggerEffectsActive();
	void AddStaggerArmor(float UnscaledArmorAmount, float ArmorDuration, int32 Player_Count, struct FGuid* ArmorGUID);
	void ReduceArmor(float Amount, float* AmountRemaining);
	void GetTotalArmor(float* TotalArmor, float* TotalInitalArmor);
	void RetroactivelyAdjustStaggerHealthForPlayerCount(int32 Player_Count);

	void GetPlayerScalingFactor(int32 Player_Count, float* ScalingFactor) const;
	void GetStaggerMaxHealthForStage(int32 Stage, int32 Player_Count, float* Max_Health) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("staggerable_bpc_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"staggerable_bpc_C")
	}
	static class Ustaggerable_bpc_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Ustaggerable_bpc_C>();
	}
};
DUMPER7_ASSERTS_Ustaggerable_bpc_C;

SDK_NAMESPACE_END
