#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: status_effect_frozen_local_ab

#include "Basic.hpp"

#include "status_effect_frozen_ab_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass status_effect_frozen_local_ab.status_effect_frozen_local_ab_C
// 0x0000 (0x0428 - 0x0428)
class Ustatus_effect_frozen_local_ab_C final : public Ustatus_effect_frozen_ab_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("status_effect_frozen_local_ab_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"status_effect_frozen_local_ab_C")
	}
	static class Ustatus_effect_frozen_local_ab_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Ustatus_effect_frozen_local_ab_C>();
	}
};
DUMPER7_ASSERTS_Ustatus_effect_frozen_local_ab_C;

SDK_NAMESPACE_END
