#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SteelSeriesGameSense

#include "Basic.hpp"


SDK_NAMESPACE_START

// Enum SteelSeriesGameSense.ESSGS_IlluminationMode
// NumValues: 0x0004
enum class ESSGS_IlluminationMode : uint8
{
	Color                                    = 0,
	Percent                                  = 1,
	Count                                    = 2,
	ESSGS_MAX                                = 3,
};

// Enum SteelSeriesGameSense.ESSGS_ColorEffect
// NumValues: 0x0004
enum class ESSGS_ColorEffect : uint8
{
	Static                                   = 0,
	Gradient                                 = 1,
	Ranges                                   = 2,
	ESSGS_MAX                                = 3,
};

// Enum SteelSeriesGameSense.ESSGS_EventIconId
// NumValues: 0x001A
enum class ESSGS_EventIconId : uint8
{
	Default                                  = 0,
	Health                                   = 1,
	Armor                                    = 2,
	Ammo                                     = 3,
	Money                                    = 4,
	Flashbang                                = 5,
	Kills                                    = 6,
	Headshot                                 = 7,
	Helmet                                   = 8,
	Hunger                                   = 10,
	Air                                      = 11,
	Compass                                  = 12,
	Tool                                     = 13,
	Mana                                     = 14,
	Clock                                    = 15,
	Lightning                                = 16,
	Item                                     = 17,
	AtSymbol                                 = 18,
	Muted                                    = 19,
	Talking                                  = 20,
	Connect                                  = 21,
	Disconnect                               = 22,
	Music                                    = 23,
	Play                                     = 24,
	Pause                                    = 25,
	ESSGS_MAX                                = 26,
};

// ScriptStruct SteelSeriesGameSense.SSGS_RGB
// 0x0003 (0x0003 - 0x0000)
struct FSSGS_RGB final
{
public:
	uint8                                         red;                                               // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         green;                                             // 0x0001(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         blue;                                              // 0x0002(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSSGS_RGB;

// ScriptStruct SteelSeriesGameSense.SSGS_Gradient
// 0x0006 (0x0006 - 0x0000)
struct FSSGS_Gradient final
{
public:
	struct FSSGS_RGB                              Zero;                                              // 0x0000(0x0003)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	struct FSSGS_RGB                              hundred;                                           // 0x0003(0x0003)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSSGS_Gradient;

// ScriptStruct SteelSeriesGameSense.SSGS_ColorGradient
// 0x0006 (0x0006 - 0x0000)
struct FSSGS_ColorGradient final
{
public:
	struct FSSGS_Gradient                         Gradient;                                          // 0x0000(0x0006)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSSGS_ColorGradient;

// ScriptStruct SteelSeriesGameSense.SSGS_JsonConvertable
// 0x0008 (0x0008 - 0x0000)
struct alignas(0x08) FSSGS_JsonConvertable
{
public:
	uint8                                         Pad_0[0x8];                                        // 0x0000(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FSSGS_JsonConvertable;

// ScriptStruct SteelSeriesGameSense.SSGS_ColorRange
// 0x0018 (0x0020 - 0x0008)
struct FSSGS_ColorRange final : public FSSGS_JsonConvertable
{
public:
	uint8                                         Pad_8[0x18];                                       // 0x0008(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FSSGS_ColorRange;

// ScriptStruct SteelSeriesGameSense.SSGS_ColorRangeGradient
// 0x0010 (0x0010 - 0x0000)
struct FSSGS_ColorRangeGradient final
{
public:
	int32                                         Low;                                               // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         High;                                              // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FSSGS_ColorGradient                    Color;                                             // 0x0008(0x0006)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_E[0x2];                                        // 0x000E(0x0002)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FSSGS_ColorRangeGradient;

// ScriptStruct SteelSeriesGameSense.SSGS_ColorRangeStatic
// 0x000C (0x000C - 0x0000)
struct FSSGS_ColorRangeStatic final
{
public:
	int32                                         Low;                                               // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         High;                                              // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FSSGS_RGB                              Color;                                             // 0x0008(0x0003)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, NativeAccessSpecifierPublic)
	uint8                                         Pad_B[0x1];                                        // 0x000B(0x0001)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FSSGS_ColorRangeStatic;

// ScriptStruct SteelSeriesGameSense.SSGS_ScreenDeviceZone
// 0x0028 (0x0028 - 0x0000)
struct alignas(0x08) FSSGS_ScreenDeviceZone final
{
public:
	uint8                                         Pad_0[0x28];                                       // 0x0000(0x0028)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FSSGS_ScreenDeviceZone;

// ScriptStruct SteelSeriesGameSense.SSGS_TactileDeviceZone
// 0x0020 (0x0020 - 0x0000)
struct alignas(0x08) FSSGS_TactileDeviceZone final
{
public:
	uint8                                         Pad_0[0x20];                                       // 0x0000(0x0020)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FSSGS_TactileDeviceZone;

// ScriptStruct SteelSeriesGameSense.SSGS_IlluminationDeviceZone
// 0x0038 (0x0038 - 0x0000)
struct alignas(0x08) FSSGS_IlluminationDeviceZone final
{
public:
	uint8                                         Pad_0[0x38];                                       // 0x0000(0x0038)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FSSGS_IlluminationDeviceZone;

// ScriptStruct SteelSeriesGameSense.SSGS_EventData
// 0x0010 (0x0018 - 0x0008)
struct FSSGS_EventData final : public FSSGS_JsonConvertable
{
public:
	int32                                         Value;                                             // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USSGS_Frame*                            frame;                                             // 0x0010(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSSGS_EventData;

// ScriptStruct SteelSeriesGameSense.SSGS_FrameData
// 0x00A0 (0x00A8 - 0x0008)
struct FSSGS_FrameData final : public FSSGS_JsonConvertable
{
public:
	uint8                                         Pad_8[0xA0];                                       // 0x0008(0x00A0)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FSSGS_FrameData;

// ScriptStruct SteelSeriesGameSense.SSGS_FrameModifiers
// 0x0010 (0x0018 - 0x0008)
struct FSSGS_FrameModifiers final : public FSSGS_JsonConvertable
{
public:
	int32                                         length_millis;                                     // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_C[0xC];                                        // 0x000C(0x000C)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FSSGS_FrameModifiers;

// ScriptStruct SteelSeriesGameSense.SSGS_FrameDataImage
// 0x0050 (0x0058 - 0x0008)
struct FSSGS_FrameDataImage final : public FSSGS_JsonConvertable
{
public:
	TArray<uint8>                                 ImageData;                                         // 0x0008(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FSSGS_FrameModifiers                   frameModifiers;                                    // 0x0018(0x0018)(NativeAccessSpecifierPublic)
	uint8                                         Pad_30[0x28];                                      // 0x0030(0x0028)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FSSGS_FrameDataImage;

// ScriptStruct SteelSeriesGameSense.SSGS_LineData
// 0x0060 (0x0068 - 0x0008)
struct FSSGS_LineData final : public FSSGS_JsonConvertable
{
public:
	uint8                                         Pad_8[0x60];                                       // 0x0008(0x0060)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FSSGS_LineData;

// ScriptStruct SteelSeriesGameSense.SSGS_FrameDataMultiLine
// 0x0030 (0x0038 - 0x0008)
struct FSSGS_FrameDataMultiLine final : public FSSGS_JsonConvertable
{
public:
	TArray<struct FSSGS_LineData>                 lines;                                             // 0x0008(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FSSGS_FrameModifiers                   frameModifiers;                                    // 0x0018(0x0018)(NativeAccessSpecifierPublic)
	ESSGS_EventIconId                             icon_id;                                           // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FSSGS_FrameDataMultiLine;

// ScriptStruct SteelSeriesGameSense.SSGS_FrameDataRange
// 0x0018 (0x0020 - 0x0008)
struct FSSGS_FrameDataRange final : public FSSGS_JsonConvertable
{
public:
	int32                                         Low;                                               // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         High;                                              // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FSSGS_FrameData>                datas;                                             // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSSGS_FrameDataRange;

// ScriptStruct SteelSeriesGameSense.SSGS_FrameDataSingleLine
// 0x0088 (0x0090 - 0x0008)
struct FSSGS_FrameDataSingleLine final : public FSSGS_JsonConvertable
{
public:
	struct FSSGS_LineData                         lineData;                                          // 0x0008(0x0068)(NativeAccessSpecifierPublic)
	struct FSSGS_FrameModifiers                   frameModifiers;                                    // 0x0070(0x0018)(NativeAccessSpecifierPublic)
	ESSGS_EventIconId                             icon_id;                                           // 0x0088(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_89[0x7];                                       // 0x0089(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FSSGS_FrameDataSingleLine;

// ScriptStruct SteelSeriesGameSense.SSGS_KeyValuePair
// 0x0038 (0x0040 - 0x0008)
struct FSSGS_KeyValuePair final : public FSSGS_JsonConvertable
{
public:
	uint8                                         Pad_8[0x38];                                       // 0x0008(0x0038)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FSSGS_KeyValuePair;

// ScriptStruct SteelSeriesGameSense.SSGS_PropertyContainer
// 0x0010 (0x0010 - 0x0000)
struct FSSGS_PropertyContainer final
{
public:
	TArray<struct FSSGS_KeyValuePair>             properties;                                        // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSSGS_PropertyContainer;

// ScriptStruct SteelSeriesGameSense.SSGS_Frequency
// 0x000C (0x000C - 0x0000)
struct FSSGS_Frequency final
{
public:
	int32                                         Low;                                               // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         High;                                              // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         frequency;                                         // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSSGS_Frequency;

// ScriptStruct SteelSeriesGameSense.SSGS_FrequencyRepeatLimitPair
// 0x0010 (0x0010 - 0x0000)
struct FSSGS_FrequencyRepeatLimitPair final
{
public:
	int32                                         Low;                                               // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         High;                                              // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         frequency;                                         // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         repeat_limit;                                      // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSSGS_FrequencyRepeatLimitPair;

// ScriptStruct SteelSeriesGameSense.SSGS_HandlerColor
// 0x0050 (0x0058 - 0x0008)
struct FSSGS_HandlerColor final : public FSSGS_JsonConvertable
{
public:
	struct FSSGS_IlluminationDeviceZone           deviceZone;                                        // 0x0008(0x0038)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	ESSGS_IlluminationMode                        Mode;                                              // 0x0040(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USSGS_ColorEffectSpecification*         Color;                                             // 0x0048(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USSGS_RateSpecification*                Rate;                                              // 0x0050(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSSGS_HandlerColor;

// ScriptStruct SteelSeriesGameSense.SSGS_HandlerScreen
// 0x0040 (0x0048 - 0x0008)
struct FSSGS_HandlerScreen final : public FSSGS_JsonConvertable
{
public:
	struct FSSGS_ScreenDeviceZone                 deviceZone;                                        // 0x0008(0x0028)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	class FString                                 Mode;                                              // 0x0030(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USSGS_ScreenDataSpecification*          Data;                                              // 0x0040(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSSGS_HandlerScreen;

// ScriptStruct SteelSeriesGameSense.SSGS_HandlerTactile
// 0x0040 (0x0048 - 0x0008)
struct FSSGS_HandlerTactile final : public FSSGS_JsonConvertable
{
public:
	struct FSSGS_TactileDeviceZone                deviceZone;                                        // 0x0008(0x0020)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	class FString                                 Mode;                                              // 0x0028(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USSGS_TactilePatternSpecification*      pattern;                                           // 0x0038(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class USSGS_RateSpecification*                Rate;                                              // 0x0040(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSSGS_HandlerTactile;

// ScriptStruct SteelSeriesGameSense.SSGS_LineDataText
// 0x0030 (0x0030 - 0x0000)
struct FSSGS_LineDataText final
{
public:
	bool                                          has_text;                                          // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 prefix;                                            // 0x0008(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 suffix;                                            // 0x0018(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Bold;                                              // 0x0028(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         wrap;                                              // 0x002C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSSGS_LineDataText;

// ScriptStruct SteelSeriesGameSense.SSGS_LineDataAccessor
// 0x0018 (0x0020 - 0x0008)
struct FSSGS_LineDataAccessor final : public FSSGS_JsonConvertable
{
public:
	uint8                                         Pad_8[0x18];                                       // 0x0008(0x0018)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FSSGS_LineDataAccessor;

// ScriptStruct SteelSeriesGameSense.ServerProps
// 0x0010 (0x0010 - 0x0000)
struct FServerProps final
{
public:
	class FString                                 Address;                                           // 0x0000(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FServerProps;

// ScriptStruct SteelSeriesGameSense.SSGS_EventUpdate
// 0x0038 (0x0040 - 0x0008)
struct FSSGS_EventUpdate final : public FSSGS_JsonConvertable
{
public:
	class FString                                 Game;                                              // 0x0008(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 EventName;                                         // 0x0018(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FSSGS_EventData                        Data;                                              // 0x0028(0x0018)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSSGS_EventUpdate;

// ScriptStruct SteelSeriesGameSense.SSGS_MultiEventUpdate
// 0x0020 (0x0028 - 0x0008)
struct FSSGS_MultiEventUpdate final : public FSSGS_JsonConvertable
{
public:
	class FString                                 Game;                                              // 0x0008(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FSSGS_EventUpdate>              _events;                                           // 0x0018(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSSGS_MultiEventUpdate;

// ScriptStruct SteelSeriesGameSense.SSGS_Game
// 0x0010 (0x0018 - 0x0008)
struct FSSGS_Game final : public FSSGS_JsonConvertable
{
public:
	class FString                                 Game;                                              // 0x0008(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSSGS_Game;

// ScriptStruct SteelSeriesGameSense.SSGS_Event
// 0x0020 (0x0028 - 0x0008)
struct FSSGS_Event final : public FSSGS_JsonConvertable
{
public:
	class FString                                 Game;                                              // 0x0008(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 EventName;                                         // 0x0018(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSSGS_Event;

// ScriptStruct SteelSeriesGameSense.SSGS_EventBinding
// 0x0038 (0x0040 - 0x0008)
struct FSSGS_EventBinding final : public FSSGS_JsonConvertable
{
public:
	class FString                                 Game;                                              // 0x0008(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 EventName;                                         // 0x0018(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MinValue;                                          // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MaxValue;                                          // 0x002C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ESSGS_EventIconId                             iconId;                                            // 0x0030(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          valueOptional;                                     // 0x0031(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_32[0x6];                                       // 0x0032(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class USSGS_HandlerCollection*                handlers;                                          // 0x0038(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSSGS_EventBinding;

// ScriptStruct SteelSeriesGameSense.SSGS_EventInfo
// 0x0030 (0x0038 - 0x0008)
struct FSSGS_EventInfo final : public FSSGS_JsonConvertable
{
public:
	class FString                                 Game;                                              // 0x0008(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 EventName;                                         // 0x0018(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MinValue;                                          // 0x0028(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MaxValue;                                          // 0x002C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	ESSGS_EventIconId                             iconId;                                            // 0x0030(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          valueOptional;                                     // 0x0031(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_32[0x6];                                       // 0x0032(0x0006)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FSSGS_EventInfo;

// ScriptStruct SteelSeriesGameSense.SSGS_GameInfo
// 0x0030 (0x0038 - 0x0008)
struct FSSGS_GameInfo final : public FSSGS_JsonConvertable
{
public:
	class FString                                 Game;                                              // 0x0008(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 gameDisplayName;                                   // 0x0018(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 developer;                                         // 0x0028(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSSGS_GameInfo;

// ScriptStruct SteelSeriesGameSense.SSGS_PredefinedTactilePattern
// 0x0010 (0x0010 - 0x0000)
struct FSSGS_PredefinedTactilePattern final
{
public:
	class FString                                 Name;                                              // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSSGS_PredefinedTactilePattern;

// ScriptStruct SteelSeriesGameSense.SSGS_RepeatLimit
// 0x000C (0x000C - 0x0000)
struct FSSGS_RepeatLimit final
{
public:
	int32                                         Low;                                               // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         High;                                              // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         repeat_limit;                                      // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSSGS_RepeatLimit;

// ScriptStruct SteelSeriesGameSense.SSGS_RateRange
// 0x0020 (0x0020 - 0x0000)
struct FSSGS_RateRange final
{
public:
	TArray<struct FSSGS_Frequency>                frequency;                                         // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FSSGS_RepeatLimit>              repeat_limit;                                      // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSSGS_RateRange;

// ScriptStruct SteelSeriesGameSense.SSGS_RateStatic
// 0x0008 (0x0008 - 0x0000)
struct FSSGS_RateStatic final
{
public:
	int32                                         frequency;                                         // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         repeat_limit;                                      // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSSGS_RateStatic;

// ScriptStruct SteelSeriesGameSense.SSGS_TactileEffectCustom
// 0x0018 (0x0020 - 0x0008)
struct FSSGS_TactileEffectCustom final : public FSSGS_JsonConvertable
{
public:
	int32                                         length_ms;                                         // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         delay_ms;                                          // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_10[0x10];                                      // 0x0010(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FSSGS_TactileEffectCustom;

// ScriptStruct SteelSeriesGameSense.SSGS_TactileEffectPredefined
// 0x0018 (0x0020 - 0x0008)
struct FSSGS_TactileEffectPredefined final : public FSSGS_JsonConvertable
{
public:
	struct FSSGS_PredefinedTactilePattern         Type;                                              // 0x0008(0x0010)(Edit, BlueprintVisible, NativeAccessSpecifierPublic)
	int32                                         delay_ms;                                          // 0x0018(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FSSGS_TactileEffectPredefined;

// ScriptStruct SteelSeriesGameSense.SSGS_TactilePatternStatic
// 0x0030 (0x0038 - 0x0008)
struct FSSGS_TactilePatternStatic final : public FSSGS_JsonConvertable
{
public:
	uint8                                         Pad_8[0x30];                                       // 0x0008(0x0030)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
DUMPER7_ASSERTS_FSSGS_TactilePatternStatic;

// ScriptStruct SteelSeriesGameSense.SSGS_TactilePatternRange
// 0x0018 (0x0020 - 0x0008)
struct FSSGS_TactilePatternRange final : public FSSGS_JsonConvertable
{
public:
	int32                                         Low;                                               // 0x0008(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         High;                                              // 0x000C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TArray<struct FSSGS_TactilePatternStatic>     pattern;                                           // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
DUMPER7_ASSERTS_FSSGS_TactilePatternRange;

SDK_NAMESPACE_END
