#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: umg_spawn_interaction_bp

#include "Basic.hpp"

#include "umg_spawn_interaction_bp_classes.hpp"
#include "umg_spawn_interaction_bp_parameters.hpp"


SDK_NAMESPACE_START

// Function umg_spawn_interaction_bp.umg_spawn_interaction_bp_C.ExecuteUbergraph_umg_spawn_interaction_bp
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Aumg_spawn_interaction_bp_C::ExecuteUbergraph_umg_spawn_interaction_bp(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawn_interaction_bp_C", "ExecuteUbergraph_umg_spawn_interaction_bp");

	Params::umg_spawn_interaction_bp_C_ExecuteUbergraph_umg_spawn_interaction_bp Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function umg_spawn_interaction_bp.umg_spawn_interaction_bp_C.ExecutePayload
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            SuccessfulInteractor                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Aumg_spawn_interaction_bp_C::ExecutePayload(class APawn* SuccessfulInteractor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawn_interaction_bp_C", "ExecutePayload");

	Params::umg_spawn_interaction_bp_C_ExecutePayload Parms{};

	Parms.SuccessfulInteractor = SuccessfulInteractor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function umg_spawn_interaction_bp.umg_spawn_interaction_bp_C.OnUserCompletedInteraction
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UArchonInteractionUserComponent*  User                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Aumg_spawn_interaction_bp_C::OnUserCompletedInteraction(class UArchonInteractionUserComponent* User)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawn_interaction_bp_C", "OnUserCompletedInteraction");

	Params::umg_spawn_interaction_bp_C_OnUserCompletedInteraction Parms{};

	Parms.User = User;

	UObject::ProcessEvent(Func, &Parms);
}


// Function umg_spawn_interaction_bp.umg_spawn_interaction_bp_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void Aumg_spawn_interaction_bp_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawn_interaction_bp_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function umg_spawn_interaction_bp.umg_spawn_interaction_bp_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void Aumg_spawn_interaction_bp_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawn_interaction_bp_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function umg_spawn_interaction_bp.umg_spawn_interaction_bp_C.CreateWidgetAndAddToViewport
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AController*                      PlayerController                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Aumg_spawn_interaction_bp_C::CreateWidgetAndAddToViewport(class AController* PlayerController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawn_interaction_bp_C", "CreateWidgetAndAddToViewport");

	Params::umg_spawn_interaction_bp_C_CreateWidgetAndAddToViewport Parms{};

	Parms.PlayerController = PlayerController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function umg_spawn_interaction_bp.umg_spawn_interaction_bp_C.CanUserStartInteraction 
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UArchonInteractionUserComponent*  User                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   CanUse                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)

void Aumg_spawn_interaction_bp_C::CanUserStartInteraction_(class UArchonInteractionUserComponent* User, bool* CanUse)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawn_interaction_bp_C", "CanUserStartInteraction ");

	Params::umg_spawn_interaction_bp_C_CanUserStartInteraction_ Parms{};

	Parms.User = User;

	UObject::ProcessEvent(Func, &Parms);

	if (CanUse != nullptr)
		*CanUse = Parms.CanUse;
}


// Function umg_spawn_interaction_bp.umg_spawn_interaction_bp_C.ChangeLocalAvailabilityOfActor
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Available_                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void Aumg_spawn_interaction_bp_C::ChangeLocalAvailabilityOfActor(bool Available_)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawn_interaction_bp_C", "ChangeLocalAvailabilityOfActor");

	Params::umg_spawn_interaction_bp_C_ChangeLocalAvailabilityOfActor Parms{};

	Parms.Available_ = Available_;

	UObject::ProcessEvent(Func, &Parms);
}


// Function umg_spawn_interaction_bp.umg_spawn_interaction_bp_C.OnRep_LocallyAvailable
// (BlueprintCallable, BlueprintEvent)

void Aumg_spawn_interaction_bp_C::OnRep_LocallyAvailable()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawn_interaction_bp_C", "OnRep_LocallyAvailable");

	UObject::ProcessEvent(Func, nullptr);
}


// Function umg_spawn_interaction_bp.umg_spawn_interaction_bp_C.GetMarkerComponent
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class UMarkerComponent*                 ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UMarkerComponent* Aumg_spawn_interaction_bp_C::GetMarkerComponent() const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("umg_spawn_interaction_bp_C", "GetMarkerComponent");

	Params::umg_spawn_interaction_bp_C_GetMarkerComponent Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
