#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_InteractionCallout

#include "Basic.hpp"

#include "AkAudio_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function UMG_InteractionCallout.UMG_InteractionCallout_C.ExecuteUbergraph_UMG_InteractionCallout
// 0x0070 (0x0070 - 0x0000)
struct UMG_InteractionCallout_C_ExecuteUbergraph_UMG_InteractionCallout final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture2D*                             K2Node_Event_DisabledIcon;                         // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(class UObject* WorldContext, EAkCallbackType CallbackType, int32 PlayingID, float EstimatedDuration)> Temp_delegate_Variable; // 0x0010(0x0010)(ConstParm, ZeroConstructor, NoDestructor)
	TDelegate<void(class UObject* WorldContext, EAkCallbackType CallbackType, int32 PlayingID, float EstimatedDuration)> Temp_delegate_Variable_1; // 0x0020(0x0010)(ConstParm, ZeroConstructor, NoDestructor)
	class APawn*                                  CallFunc_GetPlayerPawn_ReturnValue;                // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  K2Node_Event_UsingPawn_1;                          // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  K2Node_Event_UsingPawn;                            // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_Duration;                             // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsLocallyControlled_ReturnValue;          // 0x004C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsLocallyControlled_ReturnValue_1;        // 0x004D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_NewIsDisabled;                        // 0x004E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_4F[0x1];                                       // 0x004F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_Event_DisabledReason;                       // 0x0050(0x0018)()
	class UTexture2D*                             K2Node_Event_DisabledIcon_1;                       // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UMG_InteractionCallout_C_ExecuteUbergraph_UMG_InteractionCallout;

// Function UMG_InteractionCallout.UMG_InteractionCallout_C.SetShowDisabledIconWhenEnabled
// 0x0008 (0x0008 - 0x0000)
struct UMG_InteractionCallout_C_SetShowDisabledIconWhenEnabled final
{
public:
	class UTexture2D*                             DisabledIcon_0;                                    // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UMG_InteractionCallout_C_SetShowDisabledIconWhenEnabled;

// Function UMG_InteractionCallout.UMG_InteractionCallout_C.SetDisabled
// 0x0028 (0x0028 - 0x0000)
struct UMG_InteractionCallout_C_SetDisabled final
{
public:
	bool                                          NewIsDisabled;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   DisabledReason_0;                                  // 0x0008(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	class UTexture2D*                             DisabledIcon_0;                                    // 0x0020(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UMG_InteractionCallout_C_SetDisabled;

// Function UMG_InteractionCallout.UMG_InteractionCallout_C.StartFill
// 0x0010 (0x0010 - 0x0000)
struct UMG_InteractionCallout_C_StartFill final
{
public:
	class APawn*                                  UsingPawn;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Duration;                                          // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UMG_InteractionCallout_C_StartFill;

// Function UMG_InteractionCallout.UMG_InteractionCallout_C.CancelFill
// 0x0008 (0x0008 - 0x0000)
struct UMG_InteractionCallout_C_CancelFill final
{
public:
	class APawn*                                  UsingPawn;                                         // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_UMG_InteractionCallout_C_CancelFill;

// Function UMG_InteractionCallout.UMG_InteractionCallout_C.SetNoRezMessage
// 0x0020 (0x0020 - 0x0000)
struct UMG_InteractionCallout_C_SetNoRezMessage final
{
public:
	class FText                                   Message;                                           // 0x0000(0x0018)(BlueprintVisible, BlueprintReadOnly, Parm)
	bool                                          CallFunc_IsVisible_ReturnValue;                    // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
DUMPER7_ASSERTS_UMG_InteractionCallout_C_SetNoRezMessage;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
