#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: vfx_bpc

#include "Basic.hpp"

#include "vfx_bpc_classes.hpp"
#include "vfx_bpc_parameters.hpp"


SDK_NAMESPACE_START

// Function vfx_bpc.vfx_bpc_C.ExecuteUbergraph_vfx_bpc
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uvfx_bpc_C::ExecuteUbergraph_vfx_bpc(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "ExecuteUbergraph_vfx_bpc");

	Params::vfx_bpc_C_ExecuteUbergraph_vfx_bpc Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function vfx_bpc.vfx_bpc_C.ActivateVFX
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// Evfx_states                             VFXName                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uvfx_bpc_C::ActivateVFX(Evfx_states VFXName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "ActivateVFX");

	Params::vfx_bpc_C_ActivateVFX Parms{};

	Parms.VFXName = VFXName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function vfx_bpc.vfx_bpc_C.Initialize
// (BlueprintCallable, BlueprintEvent)

void Uvfx_bpc_C::Initialize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "Initialize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function vfx_bpc.vfx_bpc_C.RemoveVFX
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// Evfx_states                             VFXName                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uvfx_bpc_C::RemoveVFX(Evfx_states VFXName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "RemoveVFX");

	Params::vfx_bpc_C_RemoveVFX Parms{};

	Parms.VFXName = VFXName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function vfx_bpc.vfx_bpc_C.AddVFX
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// Evfx_states                             VFXName                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EElementalTypes                         Element                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uvfx_bpc_C::AddVFX(Evfx_states VFXName, EElementalTypes Element)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "AddVFX");

	Params::vfx_bpc_C_AddVFX Parms{};

	Parms.VFXName = VFXName;
	Parms.Element = Element;

	UObject::ProcessEvent(Func, &Parms);
}


// Function vfx_bpc.vfx_bpc_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uvfx_bpc_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "ReceiveTick");

	Params::vfx_bpc_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function vfx_bpc.vfx_bpc_C.ShowDebugInfo
// (Public, BlueprintCallable, BlueprintEvent)

void Uvfx_bpc_C::ShowDebugInfo()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "ShowDebugInfo");

	UObject::ProcessEvent(Func, nullptr);
}


// Function vfx_bpc.vfx_bpc_C.SetupArchonCharacter
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AArchonCharacter*                 ArchonCharacter                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uvfx_bpc_C::SetupArchonCharacter(class AArchonCharacter* ArchonCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "SetupArchonCharacter");

	Params::vfx_bpc_C_SetupArchonCharacter Parms{};

	Parms.ArchonCharacter = ArchonCharacter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function vfx_bpc.vfx_bpc_C.SetupPaperDoll
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APaperDoll*                       PaperDoll                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uvfx_bpc_C::SetupPaperDoll(class APaperDoll* PaperDoll)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "SetupPaperDoll");

	Params::vfx_bpc_C_SetupPaperDoll Parms{};

	Parms.PaperDoll = PaperDoll;

	UObject::ProcessEvent(Func, &Parms);
}


// Function vfx_bpc.vfx_bpc_C.StoreCharacterMaterials
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void Uvfx_bpc_C::StoreCharacterMaterials()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "StoreCharacterMaterials");

	UObject::ProcessEvent(Func, nullptr);
}


// Function vfx_bpc.vfx_bpc_C.StoreArmourMaterials
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void Uvfx_bpc_C::StoreArmourMaterials()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "StoreArmourMaterials");

	UObject::ProcessEvent(Func, nullptr);
}


// Function vfx_bpc.vfx_bpc_C.CycleThroughDataRows
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void Uvfx_bpc_C::CycleThroughDataRows()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "CycleThroughDataRows");

	UObject::ProcessEvent(Func, nullptr);
}


// Function vfx_bpc.vfx_bpc_C.SetupWeapon
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AArchonWeapon*                    Weapon_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uvfx_bpc_C::SetupWeapon(class AArchonWeapon* Weapon_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "SetupWeapon");

	Params::vfx_bpc_C_SetupWeapon Parms{};

	Parms.Weapon_0 = Weapon_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function vfx_bpc.vfx_bpc_C.StoreWeaponMaterials
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void Uvfx_bpc_C::StoreWeaponMaterials()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "StoreWeaponMaterials");

	UObject::ProcessEvent(Func, nullptr);
}


// Function vfx_bpc.vfx_bpc_C.OnActivate_EyeGlow
// (Public, BlueprintCallable, BlueprintEvent)

void Uvfx_bpc_C::OnActivate_EyeGlow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "OnActivate_EyeGlow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function vfx_bpc.vfx_bpc_C.OnActivate_EyeRage
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void Uvfx_bpc_C::OnActivate_EyeRage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "OnActivate_EyeRage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function vfx_bpc.vfx_bpc_C.OnActivate_EyeRageHeroHelm
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void Uvfx_bpc_C::OnActivate_EyeRageHeroHelm()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "OnActivate_EyeRageHeroHelm");

	UObject::ProcessEvent(Func, nullptr);
}


// Function vfx_bpc.vfx_bpc_C.OnDeactivate_EyeGlow
// (Public, BlueprintCallable, BlueprintEvent)

void Uvfx_bpc_C::OnDeactivate_EyeGlow()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "OnDeactivate_EyeGlow");

	UObject::ProcessEvent(Func, nullptr);
}


// Function vfx_bpc.vfx_bpc_C.OnDeactivate_EyeRage
// (Public, BlueprintCallable, BlueprintEvent)

void Uvfx_bpc_C::OnDeactivate_EyeRage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "OnDeactivate_EyeRage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function vfx_bpc.vfx_bpc_C.OnDeactivate_EyeRageHeroHelm
// (Public, BlueprintCallable, BlueprintEvent)

void Uvfx_bpc_C::OnDeactivate_EyeRageHeroHelm()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "OnDeactivate_EyeRageHeroHelm");

	UObject::ProcessEvent(Func, nullptr);
}


// Function vfx_bpc.vfx_bpc_C.UpdateVFX
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uvfx_bpc_C::UpdateVFX(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "UpdateVFX");

	Params::vfx_bpc_C_UpdateVFX Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function vfx_bpc.vfx_bpc_C.GetActiveVFXData
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// Evfx_states                             VFX                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct Fvfx_struct*                     Data                                                   (Parm, OutParm, HasGetValueTypeHash)

void Uvfx_bpc_C::GetActiveVFXData(Evfx_states VFX, struct Fvfx_struct* Data)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "GetActiveVFXData");

	Params::vfx_bpc_C_GetActiveVFXData Parms{};

	Parms.VFX = VFX;

	UObject::ProcessEvent(Func, &Parms);

	if (Data != nullptr)
		*Data = std::move(Parms.Data);
}


// Function vfx_bpc.vfx_bpc_C.OnActivate_WeaponGlow
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// Evfx_states                             VFX                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uvfx_bpc_C::OnActivate_WeaponGlow(Evfx_states VFX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "OnActivate_WeaponGlow");

	Params::vfx_bpc_C_OnActivate_WeaponGlow Parms{};

	Parms.VFX = VFX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function vfx_bpc.vfx_bpc_C.SetVFXVectorData
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// Evfx_states                             VFX                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName                             Name_0                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   Vector                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uvfx_bpc_C::SetVFXVectorData(Evfx_states VFX, class FName Name_0, const struct FVector& Vector)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "SetVFXVectorData");

	Params::vfx_bpc_C_SetVFXVectorData Parms{};

	Parms.VFX = VFX;
	Parms.Name_0 = Name_0;
	Parms.Vector = std::move(Vector);

	UObject::ProcessEvent(Func, &Parms);
}


// Function vfx_bpc.vfx_bpc_C.RemoveExpiredVFX
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void Uvfx_bpc_C::RemoveExpiredVFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "RemoveExpiredVFX");

	UObject::ProcessEvent(Func, nullptr);
}


// Function vfx_bpc.vfx_bpc_C.UpdateVFXTimeActive
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uvfx_bpc_C::UpdateVFXTimeActive(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "UpdateVFXTimeActive");

	Params::vfx_bpc_C_UpdateVFXTimeActive Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function vfx_bpc.vfx_bpc_C.UpdateWeapon
// (Public, BlueprintCallable, BlueprintEvent)

void Uvfx_bpc_C::UpdateWeapon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "UpdateWeapon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function vfx_bpc.vfx_bpc_C.UpdateCharacter
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct Fmaterial_float_property_struct>&FloatProperties                                        (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// TArray<struct Fmaterial_color_property_struct>&ColorProperties                                        (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)
// TArray<struct Fmaterial_texture_property_struct>&TextureProperties                                      (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)

void Uvfx_bpc_C::UpdateCharacter(TArray<struct Fmaterial_float_property_struct>& FloatProperties, TArray<struct Fmaterial_color_property_struct>& ColorProperties, TArray<struct Fmaterial_texture_property_struct>& TextureProperties)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "UpdateCharacter");

	Params::vfx_bpc_C_UpdateCharacter Parms{};

	Parms.FloatProperties = std::move(FloatProperties);
	Parms.ColorProperties = std::move(ColorProperties);
	Parms.TextureProperties = std::move(TextureProperties);

	UObject::ProcessEvent(Func, &Parms);

	FloatProperties = std::move(Parms.FloatProperties);
	ColorProperties = std::move(Parms.ColorProperties);
	TextureProperties = std::move(Parms.TextureProperties);
}


// Function vfx_bpc.vfx_bpc_C.OnActivate_ACPlayerBodyPip
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// Evfx_states                             VFX                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uvfx_bpc_C::OnActivate_ACPlayerBodyPip(Evfx_states VFX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "OnActivate_ACPlayerBodyPip");

	Params::vfx_bpc_C_OnActivate_ACPlayerBodyPip Parms{};

	Parms.VFX = VFX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function vfx_bpc.vfx_bpc_C.SetupComponentList
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// Evfx_states                             VFX                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<Evfx_components>*                Components                                             (Parm, OutParm, HasGetValueTypeHash)

void Uvfx_bpc_C::SetupComponentList(Evfx_states VFX, TArray<Evfx_components>* Components)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "SetupComponentList");

	Params::vfx_bpc_C_SetupComponentList Parms{};

	Parms.VFX = VFX;

	UObject::ProcessEvent(Func, &Parms);

	if (Components != nullptr)
		*Components = std::move(Parms.Components);
}


// Function vfx_bpc.vfx_bpc_C.SetVFXComponentData
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// Evfx_states                             VFX                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<Evfx_components>&                Components                                             (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, HasGetValueTypeHash)

void Uvfx_bpc_C::SetVFXComponentData(Evfx_states VFX, TArray<Evfx_components>& Components)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "SetVFXComponentData");

	Params::vfx_bpc_C_SetVFXComponentData Parms{};

	Parms.VFX = VFX;
	Parms.Components = std::move(Components);

	UObject::ProcessEvent(Func, &Parms);

	Components = std::move(Parms.Components);
}


// Function vfx_bpc.vfx_bpc_C.ResetOwner
// (Public, BlueprintCallable, BlueprintEvent)

void Uvfx_bpc_C::ResetOwner()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "ResetOwner");

	UObject::ProcessEvent(Func, nullptr);
}


// Function vfx_bpc.vfx_bpc_C.RestoreCharacterMaterials
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void Uvfx_bpc_C::RestoreCharacterMaterials()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "RestoreCharacterMaterials");

	UObject::ProcessEvent(Func, nullptr);
}


// Function vfx_bpc.vfx_bpc_C.RestoreAmourMaterials
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void Uvfx_bpc_C::RestoreAmourMaterials()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "RestoreAmourMaterials");

	UObject::ProcessEvent(Func, nullptr);
}


// Function vfx_bpc.vfx_bpc_C.RestoreWeaponMaterials
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void Uvfx_bpc_C::RestoreWeaponMaterials()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "RestoreWeaponMaterials");

	UObject::ProcessEvent(Func, nullptr);
}


// Function vfx_bpc.vfx_bpc_C.DeactivateVFX_Func
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// Evfx_states                             VFX                                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uvfx_bpc_C::DeactivateVFX_Func(Evfx_states VFX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "DeactivateVFX_Func");

	Params::vfx_bpc_C_DeactivateVFX_Func Parms{};

	Parms.VFX = VFX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function vfx_bpc.vfx_bpc_C.OnActivate_CelestialHelm02
// (Public, BlueprintCallable, BlueprintEvent)

void Uvfx_bpc_C::OnActivate_CelestialHelm02()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "OnActivate_CelestialHelm02");

	UObject::ProcessEvent(Func, nullptr);
}


// Function vfx_bpc.vfx_bpc_C.OnDeactivate_CelestialHelm
// (Public, BlueprintCallable, BlueprintEvent)

void Uvfx_bpc_C::OnDeactivate_CelestialHelm()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("vfx_bpc_C", "OnDeactivate_CelestialHelm");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
