#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: vfx_state_id_struct

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedStruct vfx_state_id_struct.vfx_state_id_struct
// 0x0010 (0x0010 - 0x0000)
struct Fvfx_state_id_struct final
{
public:
	class UParticleSystemComponent*               vfx_7_556FCFBC4F099E4DEA1CC191694CDB26;            // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class Udebris_event_bpns_C*                   event_6_11FF011E486E75E562CF4BB7DCE8C951;          // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_Fvfx_state_id_struct;

SDK_NAMESPACE_END
