#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: w_appearance_asset_panel_bpw

#include "Basic.hpp"

#include "AkAudio_structs.hpp"
#include "OnlineSubsystemPhoenix_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function w_appearance_asset_panel_bpw.w_appearance_asset_panel_bpw_C.ExecuteUbergraph_w_appearance_asset_panel_bpw
// 0x0218 (0x0218 - 0x0000)
struct w_appearance_asset_panel_bpw_C_ExecuteUbergraph_w_appearance_asset_panel_bpw final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FOnlineStorePhoenixPurchasableAsset    K2Node_Event_Asset;                                // 0x0008(0x01A0)(ConstParm)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x01A8(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(class UObject* WorldContext, EAkCallbackType CallbackType, int32 PlayingID, float EstimatedDuration)> Temp_delegate_Variable; // 0x01B8(0x0010)(ConstParm, ZeroConstructor, NoDestructor)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x01C8(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(class UObject* WorldContext, EAkCallbackType CallbackType, int32 PlayingID, float EstimatedDuration)> Temp_delegate_Variable_1; // 0x01D8(0x0010)(ConstParm, ZeroConstructor, NoDestructor)
	TDelegate<void(class UObject* WorldContext, EAkCallbackType CallbackType, int32 PlayingID, float EstimatedDuration)> Temp_delegate_Variable_2; // 0x01E8(0x0010)(ConstParm, ZeroConstructor, NoDestructor)
	int32                                         CallFunc_GetPopupLayer_ReturnValue;                // 0x01F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1FC[0x4];                                      // 0x01FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetOwningPlayer_ReturnValue;              // 0x0200(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class Upopup_store_purchase_bpw_C*            CallFunc_Create_ReturnValue;                       // 0x0208(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0210(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_w_appearance_asset_panel_bpw_C_ExecuteUbergraph_w_appearance_asset_panel_bpw;

// Function w_appearance_asset_panel_bpw.w_appearance_asset_panel_bpw_C.PurchaseAsset
// 0x01A0 (0x01A0 - 0x0000)
struct w_appearance_asset_panel_bpw_C_PurchaseAsset final
{
public:
	struct FOnlineStorePhoenixPurchasableAsset    Asset;                                             // 0x0000(0x01A0)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
DUMPER7_ASSERTS_w_appearance_asset_panel_bpw_C_PurchaseAsset;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
