#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: w_archoninputkey_bpw

#include "Basic.hpp"

#include "Archon_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass w_archoninputkey_bpw.w_archoninputkey_bpw_C
// 0x0008 (0x03F8 - 0x03F0)
class Uw_archoninputkey_bpw_C final : public UArchonInputKey
{
public:
	class UImage*                                 Backpiece;                                         // 0x03F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("w_archoninputkey_bpw_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"w_archoninputkey_bpw_C")
	}
	static class Uw_archoninputkey_bpw_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Uw_archoninputkey_bpw_C>();
	}
};
DUMPER7_ASSERTS_Uw_archoninputkey_bpw_C;

SDK_NAMESPACE_END
