#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: w_escalation_relic_summary

#include "Basic.hpp"

#include "Archon_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass w_escalation_relic_summary.w_escalation_relic_summary_C
// 0x0010 (0x0390 - 0x0380)
class Uw_escalation_relic_summary_C final : public UEscalationRelicSummaryWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0380(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	int32                                         TestPositioningCount;                              // 0x0388(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_w_escalation_relic_summary(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("w_escalation_relic_summary_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"w_escalation_relic_summary_C")
	}
	static class Uw_escalation_relic_summary_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Uw_escalation_relic_summary_C>();
	}
};
DUMPER7_ASSERTS_Uw_escalation_relic_summary_C;

SDK_NAMESPACE_END
