#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: w_loadout_assign_gear_weapon_tabs

#include "Basic.hpp"

#include "Archon_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass w_loadout_assign_gear_weapon_tabs.w_loadout_assign_gear_weapon_tabs_C
// 0x0008 (0x0370 - 0x0368)
class Uw_loadout_assign_gear_weapon_tabs_C final : public UArchonTabs
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0368(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_w_loadout_assign_gear_weapon_tabs(int32 EntryPoint);
	void UpdateButtonHints(const TSoftObjectPtr<class UTexture2D>& PreviousButton, const TSoftObjectPtr<class UTexture2D>& NextButton);
	void OnLoaded_A058EA6248D678A919D5DF91A44D5CAE(class UObject* Loaded);
	void OnLoaded_A058EA6248D678A919D5DF91172B33B1(class UObject* Loaded);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("w_loadout_assign_gear_weapon_tabs_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"w_loadout_assign_gear_weapon_tabs_C")
	}
	static class Uw_loadout_assign_gear_weapon_tabs_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Uw_loadout_assign_gear_weapon_tabs_C>();
	}
};
DUMPER7_ASSERTS_Uw_loadout_assign_gear_weapon_tabs_C;

SDK_NAMESPACE_END
