#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: w_options_bindings

#include "Basic.hpp"

#include "Archon_classes.hpp"
#include "Engine_structs.hpp"
#include "LocalizationFramework_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass w_options_bindings.w_options_bindings_C
// 0x0018 (0x0378 - 0x0360)
class Uw_options_bindings_C final : public UOptionsCatBindings
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0360(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	TArray<ECharacterGender>                      GenderIdentityList;                                // 0x0368(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_w_options_bindings(int32 EntryPoint);
	void OnCategorySwitched(class UWidget* FocusedCategoryWidget);
	void Construct();
	void GetGenderIdentity(ECharacterGender* GenderIdentity);
	void SetGenderIdentity(ECharacterGender Gender);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("w_options_bindings_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"w_options_bindings_C")
	}
	static class Uw_options_bindings_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Uw_options_bindings_C>();
	}
};
DUMPER7_ASSERTS_Uw_options_bindings_C;

SDK_NAMESPACE_END
