#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: w_Simple_Stat_tooltip_bpw

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass w_Simple_Stat_tooltip_bpw.w_Simple_Stat_tooltip_bpw_C
// 0x0090 (0x0368 - 0x02D8)
class Uw_Simple_Stat_tooltip_bpw_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02D8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                BorderBG;                                          // 0x02E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             StatName;                                          // 0x02E8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_131;                                     // 0x02F0(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TextBlock_132;                                     // 0x02F8(0x0008)(ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 TooltipIcon;                                       // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   Name_0;                                            // 0x0308(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)
	float                                         Value;                                             // 0x0320(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	uint8                                         Pad_324[0x4];                                      // 0x0324(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UTexture2D>              Icon;                                              // 0x0328(0x0028)(Edit, BlueprintVisible, ExposeOnSpawn, HasGetValueTypeHash)
	class FText                                   Description;                                       // 0x0350(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)

public:
	void ExecuteUbergraph_w_Simple_Stat_tooltip_bpw(int32 EntryPoint);
	void Construct();
	void OnLoaded_FCE8185C4D215A2DC53DF99741F5CABC(class UObject* Loaded);
	class FText GetText_Value();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("w_Simple_Stat_tooltip_bpw_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"w_Simple_Stat_tooltip_bpw_C")
	}
	static class Uw_Simple_Stat_tooltip_bpw_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Uw_Simple_Stat_tooltip_bpw_C>();
	}
};
DUMPER7_ASSERTS_Uw_Simple_Stat_tooltip_bpw_C;

SDK_NAMESPACE_END
