#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: w_voip_confirmation_popup_bpw

#include "Basic.hpp"

#include "w_voip_confirmation_popup_bpw_classes.hpp"
#include "w_voip_confirmation_popup_bpw_parameters.hpp"


SDK_NAMESPACE_START

// Function w_voip_confirmation_popup_bpw.w_voip_confirmation_popup_bpw_C.ExecuteUbergraph_w_voip_confirmation_popup_bpw
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uw_voip_confirmation_popup_bpw_C::ExecuteUbergraph_w_voip_confirmation_popup_bpw(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("w_voip_confirmation_popup_bpw_C", "ExecuteUbergraph_w_voip_confirmation_popup_bpw");

	Params::w_voip_confirmation_popup_bpw_C_ExecuteUbergraph_w_voip_confirmation_popup_bpw Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function w_voip_confirmation_popup_bpw.w_voip_confirmation_popup_bpw_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void Uw_voip_confirmation_popup_bpw_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("w_voip_confirmation_popup_bpw_C", "PreConstruct");

	Params::w_voip_confirmation_popup_bpw_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function w_voip_confirmation_popup_bpw.w_voip_confirmation_popup_bpw_C.SetFooterText
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bUsingGamepad                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void Uw_voip_confirmation_popup_bpw_C::SetFooterText(bool bUsingGamepad)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("w_voip_confirmation_popup_bpw_C", "SetFooterText");

	Params::w_voip_confirmation_popup_bpw_C_SetFooterText Parms{};

	Parms.bUsingGamepad = bUsingGamepad;

	UObject::ProcessEvent(Func, &Parms);
}


// Function w_voip_confirmation_popup_bpw.w_voip_confirmation_popup_bpw_C.OnInputSwap
// (Event, Public, BlueprintEvent)
// Parameters:
// const bool                              bUsingGamepad                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void Uw_voip_confirmation_popup_bpw_C::OnInputSwap(const bool bUsingGamepad)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("w_voip_confirmation_popup_bpw_C", "OnInputSwap");

	Params::w_voip_confirmation_popup_bpw_C_OnInputSwap Parms{};

	Parms.bUsingGamepad = bUsingGamepad;

	UObject::ProcessEvent(Func, &Parms);
}


// Function w_voip_confirmation_popup_bpw.w_voip_confirmation_popup_bpw_C.OnDismissPressed
// (Event, Protected, BlueprintEvent)

void Uw_voip_confirmation_popup_bpw_C::OnDismissPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("w_voip_confirmation_popup_bpw_C", "OnDismissPressed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function w_voip_confirmation_popup_bpw.w_voip_confirmation_popup_bpw_C.OnConfirmPressed
// (Event, Protected, BlueprintEvent)

void Uw_voip_confirmation_popup_bpw_C::OnConfirmPressed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("w_voip_confirmation_popup_bpw_C", "OnConfirmPressed");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
