#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: wandering_nibbler_skyfish_ai_bpc

#include "Basic.hpp"

#include "Archon_classes.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass wandering_nibbler_skyfish_ai_bpc.wandering_nibbler_skyfish_ai_bpc_C
// 0x0018 (0x0140 - 0x0128)
class Uwandering_nibbler_skyfish_ai_bpc_C final : public UArchonSkyfishAIComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0128(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class Askyfish_bp_C*                          SkyfishRef;                                        // 0x0130(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         PingSize;                                          // 0x0138(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         PingDuration;                                      // 0x013C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_wandering_nibbler_skyfish_ai_bpc(int32 EntryPoint);
	void OnSkyfishMovementFinished();
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("wandering_nibbler_skyfish_ai_bpc_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"wandering_nibbler_skyfish_ai_bpc_C")
	}
	static class Uwandering_nibbler_skyfish_ai_bpc_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<Uwandering_nibbler_skyfish_ai_bpc_C>();
	}
};
DUMPER7_ASSERTS_Uwandering_nibbler_skyfish_ai_bpc_C;

SDK_NAMESPACE_END
