#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: wandering_nibbler_skyfish_ai_bpc

#include "Basic.hpp"

#include "wandering_nibbler_skyfish_ai_bpc_classes.hpp"
#include "wandering_nibbler_skyfish_ai_bpc_parameters.hpp"


SDK_NAMESPACE_START

// Function wandering_nibbler_skyfish_ai_bpc.wandering_nibbler_skyfish_ai_bpc_C.ExecuteUbergraph_wandering_nibbler_skyfish_ai_bpc
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void Uwandering_nibbler_skyfish_ai_bpc_C::ExecuteUbergraph_wandering_nibbler_skyfish_ai_bpc(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("wandering_nibbler_skyfish_ai_bpc_C", "ExecuteUbergraph_wandering_nibbler_skyfish_ai_bpc");

	Params::wandering_nibbler_skyfish_ai_bpc_C_ExecuteUbergraph_wandering_nibbler_skyfish_ai_bpc Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function wandering_nibbler_skyfish_ai_bpc.wandering_nibbler_skyfish_ai_bpc_C.OnSkyfishMovementFinished
// (BlueprintCallable, BlueprintEvent)

void Uwandering_nibbler_skyfish_ai_bpc_C::OnSkyfishMovementFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("wandering_nibbler_skyfish_ai_bpc_C", "OnSkyfishMovementFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function wandering_nibbler_skyfish_ai_bpc.wandering_nibbler_skyfish_ai_bpc_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void Uwandering_nibbler_skyfish_ai_bpc_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("wandering_nibbler_skyfish_ai_bpc_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
